A collection of (possibly) networks of self-consistent beliefs/assertions from different political ideologies, linked together to show interrelationships, agreements, disagreements, ... Basically a fancy political quiz.

* todo / notes
- After finish anarchism and maybe a few others, stop and make a prototype of the site
- Look at notes... And ideally condense them.
- Might be useful to search for 'disagreements between A and B'
- Not sure how tree-like this will end up being - maybe will ultimately be more of a "constellation" of assertions, some of which are parts of "logical dependency" trees
- How to include critique? Like want to include the information of "criticism of capitalism", socialism, etc. pages, but not sure how best to include them. Maybe, for ideologies that explicitly critique particular ideas, just have that critique as an assertion that conflicts with the idea it's critiquing?
- Had previously thought to only have a single kind of edge / inclusion, "accepts" (rather than both "explicitly accepts" and "explicitly rejects"), but would also be kinda nice to have "sometimes accepts" - like anarcho-naturism sometimes-accepts vegetarianism, sometimes not. Not sure this is worth the complexity though - suddenly seems like every ideology should have an edge (of some sort) to every assertion. Though could have "accepts" and "sometimes accepts"...
- how to represent the evolution of ideas? often rejecting original version and accepting modified version... Maybe simplest to just have the "evolution" as a new assertion that conflicts with original idea... But not great.
- According to wikipedia: "Political ideologies have two dimensions: Goals - how society should work, and Methods - the most appropriate ways to achieve the ideal arrangement".  So maybe can have _both_ the "ideas" and the "practical things", like nodes both for goals like communal ownership, and methods like free shops, mutualist credit exchanges, and other practical / "implementation details". Then can still collect those things into your own personal ideology.
- Also just think you should have "critiques" of things as their own nodes with some kind of conflicting edge to the thing they critique.
* desirements
- want it to help you find inconsistencies in your own beliefs
- want to be able to automatically find the fundamental disagreements between two ideological poses
- list of ideologies that you can scroll through to see them get highlighted in the graph, then see them blank out as you "rule them out" while choosing assertions
- come up with a funny (but accurate) name for the current selection of assertions
- button to generate new consistent ideology and come up with a silly name
- 'justify' button that let's you choose assertions and generates a minimal set of beliefs that support them 
- Medium term goal is to be able to paste in a (maybe artificial) text, have it attempt to extract key phrases (which you can filter / remove if desired) and create a graph of ideological concepts, then automatically synthesize (ish) a response (or just point out good things to use as counterarguments) given your own ideological positions
- seeing some of the heinous shit that these philosophers thought, interesting to highlight that in the graph as well - like pick out philosophers and see that, oh, they thought races needed to be pure
- cool if can easily display difference between ideologies in site - just like you can view the 'root disagreements' (or root agreements) between two people/poses, you can enter two existing ideologies and view their differences
- secretly a propaganda tool! because thinking rationally about political position might make you realize you're not a "liberal" or "conservative"
- maybe *could* do some kind of netflix-y machine learning / recommendation engine thing. Have the rows of your matrix be particular assertions / views, and the columns be ideology names... Might be interesting to play with. Though wouldn't take advantage of logical dependencies in any way, but maybe that's ok... Probably shouldn't go by ideology names though, want to basically "discover" those through this process. Maybe should put actual individuals.
- maybe just start with a git repo with a dot graph file and a "descriptions" file (which has further information on IDs in the dot file, in markdown or something), then generate the graph from that. When you click on things, can add to your "idelogical profile" and also see more info on it, see what it contradicts (which will also be colored in / grayed out on the graph), ...
* things to integrate
- quote from hn: I honestly feel that if considered luck to be a larger factor and effort to be a lesser factor, his political stances would change pretty dramatically. (same applies to me in reverse). I wonder how much the social willingness to accept luck as a factor impacts popular political positions. (Perhaps not much, as the author in the article promotes a consumption tax, which is generally seen as more regressive)
- quote from hn: My version: Republican party platform does not believe in the "veil of ignorance" at all whatsoever. They support neo-feudalism and aristocracy. Equality is fake, people are in fact different, those differences should be rewarded and punished in a free market, it is considered unfair to force equality to be true. Even equality under the law is negotiable, where those who can afford better lawyers get better justice. Democrats are tone deaf, and suck at marketing their own policy successes. They'd rather convince people to vote for them on the basis of a smug liberalism which says if only people had the facts they'd vote Democrat. Ergo if you vote Republican you're either stupid or evil. This is not a winning strategy, obviously.
- quote from hn: Drilling in to find what we really disagree about, it seems to boil down to two concepts: (1) I view success as a matter of luck that your effort can make better or worse. He views effort as the single most important deciding factor in success in life (2) I'm willing to tolerate an amount of "unfairness" in people getting help they "don't deserve", while he finds this very offensive.
- http://townhall.com/columnists/dennisprager/2017/01/17/a-guide-to-basic-differences-between-left-and-right-n2271475
- https://en.wikipedia.org/wiki/Social_philosophy
* links
http://www.philosophyideas.com/
https://www.truthmapping.com/
http://www.iep.utm.edu/
search "x core beliefs"
* political dimensions
- Authoritarian-Libertarian (socially) vs Left-Right (economically) spectrum (politicalcompass.org)
- Nolan Chart: Personal Issues vs. Economic Issues  (Foundation for Economic Education)
- Left-Right vs. Libertarian-Statist (Advocates for Self Government)
- Economic Liberty v. Personal Liberty v. Political Liberty (http://www.friesian.com/quiz.htm)
- sociocultural issues vs economic issues - both spanning from individualism to communitarianism (https://en.wikipedia.org/wiki/Political_spectrum) - there a bunch more 'possible dimensions' listed there
- Traditional - Secular/Rational values vs.  Survival - Self Expression values (inglehart values map)
- Nolar Chart + "interventionism" dimension
* questions from political quizzes
** politicalcompass.org
If economic globalisation is inevitable, it should primarily serve humanity rather than the interests of trans-national corporations.
I'd always support my country, whether it was right or wrong.
No one chooses his or her country of birth, so it's foolish to be proud of it.
Our race has many superior qualities, compared with other races.
The enemy of my enemy is my friend.
Military action that defies international law is sometimes justified.
There is now a worrying fusion of information and entertainment.
People are ultimately divided more by class than by nationality.
Controlling inflation is more important than controlling unemployment.
Because corporations cannot be trusted to voluntarily protect the environment, they require regulation.
"from each according to his ability, to each according to his need" is a fundamentally good idea.
It's a sad reflection on our society that something as basic as drinking water is now a bottled, branded consumer product.
Land shouldn't be a commodity to be bought and sold.
It is regrettable that many personal fortunes are made by people who simply manipulate money and contribute nothing to their society.
Protectionism is sometimes necessary in trade.
The only social responsibility of a company should be to deliver a profit to its shareholders.
The rich are too highly taxed.
Those with the ability to pay should have the right to higher standards of medical care .
Governments should penalise businesses that mislead the public.
A genuine free market requires restrictions on the ability of predator multinationals to create monopolies.
The freer the market, the freer the people.
Abortion, when the woman's life is not threatened, should always be illegal.
All authority should be questioned.
An eye for an eye and a tooth for a tooth.
Taxpayers should not be expected to prop up any theatres or museums that cannot survive on a commercial basis.
Schools should not make classroom attendance compulsory.
All people have their rights, but it is better for all of us that different sorts of people should keep to their own kind.
Good parents sometimes have to spank their children.
It's natural for children to keep some secrets from their parents.
Possessing marijuana for personal use should not be a criminal offence.
The prime function of schooling should be to equip the future generation to find jobs.
People with serious inheritable disabilities should not be allowed to reproduce.
The most important thing for children to learn is to accept discipline.
There are no savage and civilised peoples; there are only different cultures.
Those who are able to work, and refuse the opportunity, should not expect society's support.
When you are troubled, it's better not to think about it, but to keep busy with more cheerful things.
First-generation immigrants can never be fully integrated within their new country.
What's good for the most successful corporations is always, ultimately, good for all of us.
No broadcasting institution, however independent its content, should receive public funding.
Our civil liberties are being excessively curbed in the name of counter-terrorism.
A significant advantage of a one-party state is that it avoids all the arguments that delay progress in a democratic political system.
Although the electronic age makes official surveillance easier, only wrongdoers need to be worried.
The death penalty should be an option for the most serious crimes.
In a civilised society, one must always have people above to be obeyed and people below to be commanded.
Abstract art that doesn't represent anything shouldn't be considered art at all.
In criminal justice, punishment should be more important than rehabilitation.
It is a waste of time to try to rehabilitate some criminals.
The businessperson and the manufacturer are more important than the writer and the artist.
Mothers may have careers, but their first duty is to be homemakers.
Multinational companies are unethically exploiting the plant genetic resources of developing countries.
Making peace with the establishment is an important aspect of maturity.
Astrology accurately explains many things.
You cannot be moral without being religious.
Charity is better than social security as a means of helping the genuinely disadvantaged.
Some people are naturally unlucky.
It is important that my child's school instills religious values.
Sex outside marriage is usually immoral.
A same sex couple in a stable, loving relationship should not be excluded from the possibility of child adoption.
Pornography, depicting consenting adults, should be legal for the adult population.
What goes on in a private bedroom between consenting adults is no business of the state.
No one can feel naturally homosexual.
These days openness about sex has gone too far.
** Advocates for Self Government "World' Smallest Policital Quiz"
Government should not censor speech, press, media, or internet. 
Military service should be voluntary. There should be no draft. 
There should be no laws regarding sex for consenting adults. 
Repeal laws prohibiting adult possession and use of drugs. 
There should be no National ID card. 
End "corporate welfare." No government handouts to business. 
End government barriers to international free trade. 
Let people control their own retirement; privatize Social Security. 
Replace government welfare with private charity. 
Cut taxes and government spending by 50% or more.
** http://www.friesian.com/quiz.htm, 3D spectrum
(Each one has yes-maybe-no answers, yes=10pts, maybe=5pts, no=0pts)
Do you have the right to...
(personal rights)
- see or buy a pornographic video
- not wear a seatbelt or motorcycle helmet
- not send your child to school
- have an abortion
- own a handgun
- have any sexual relations with adults
- travel to any foreign country
- use unapproved medical treatments
- use marijuana or other drugs
- not wear a swimsuit
(economic rights)
- offer or accept a particular wage
- hire or not a minority or foreign worker
- gamble for money
- not insure your car
- purchase foreign made products
- run a business at home
- not give money to public welfare
- support a foreign country
- not contribute to social security
- hire an unlicensed contractor
(political rights)
- vote or decline to vote in elections
- contribute any money you see fit to politicians or causes
- be compensated for the public use of your property
- decline to serve on juries
- vote your conscience while on a jury
- decline to serve in the military
- obey only lawful orders while in the military
- resist tyrannical acts or unjust laws by force
- decline to pay taxes
* collection of key assertions
** strategy
- Go through list of political ideologies
- Grab all the key concepts / tenets / core beliefs you find and put in a list (don't worry about relation)
- Cover anything you missed on the Category pages - like "Category: Libertarianism by form"
- Make sure you've gone to all the links in the "Politics Series on (xxx)" headers
- Take the rough concepts and try to extract out brief versions, so that each ideology is a list of key ideas
- Merge as many as possible, connect together, expand logical bases for them, etc.
** anarchism
LOOK AT ALL THE LINKS UNDER "politics series on anarchism" thing, make sure you've seen them all!

(grab bag of things that I wasn't sure where to put)
- the state is undesirable, unnecessary, or harmful
- violentist vs pacifist
- free love
- direct action
- propaganda by the (deed, ...)
- refusal of work
*** philosophical anarchism
- the state lacks moral legitimacy, but we should not use violence to eliminate it
- we have no obligation or duty to obey the State, and the State has no right to command us
- self-government with a "progressive rationalism that included benevolence to others
- social cooperation should be achieved via the market
- a minimal state is an unfortunate (and hopefully temporary) "necessary evil"
- we do not have a moral obligation to obey the state when its laws conflict with individual autonomy
- individuals to act in accordance with their own judgments and to allow every other individual the same liberty (godwinian)
- 'the unique one' who truly 'owns himself' recognizes no duties to others; within the limit of his might, he does what is right for him (stirnerian)
- we should work for gradual change to free the individual from what they thought were the oppressive laws and social constraints of the modern state and allow all individuals to become self-determining and value-creating
- oppose the immediate elimination of the state by violent means out of concern that what remains might be vulnerable to the establishment of a yet more harmful and oppressive state
- violence and the state are synonymous
- public reaction to violence results in increased "law enforcement" efforts.
- individualist anarchists reject both social "archy" and political "kratos"
- "conservative anarchists" accept social "archy" of rank but not political "kratos" of state control
- support the ordering by rank of social groups such as families, churches, corporations, clubs, and even countries
- government is a "necessary evil"
- the state will become increasingly unnecessary and powerless by the gradual spread of knowledge
- That government is best which governs not at all
- the state has a right to command and subjects have a binding obligation to obey
*** Herbert Spencer
- Human culture and societies should be subject to evolution ("survival of the fittest" - Herbert Spencer)
- the state was not an "essential" institution and that it would "decay" as voluntary market organisation would replace the coercive aspects of the state
- the individual has a right to ignore the state
- there is no alternative
- there should be no private property in land
- trade unions should be used as a "bulwark against bosses"
- economy organised primarily in free worker co-operatives as a replacement for wage-labor
- a slave is a person who labours under coercion to satisfy another's desires
- under socialism or communism the individual would be enslaved to the whole community rather than to a particular master
- humanitarian impulses must be resisted as nothing should be allowed to interfere with nature's laws, including the social struggle for existence
- competition means (biological competition)
- competition means competing individuals or firms improve the well being of the rest of society
- voluntary association and informal care to aid those in need, rather than relying on government bureaucracy or force
- private charitable efforts would be wise to avoid encouraging the formation of new dependent families by those unable to support themselves without charity
- races shouldn't mix...
*** subway map to anarchism
http://i.imgur.com/v9jOzQ8.png
-> gay liberation -> queer anarchism
-> anti-organized religion -> religious anarchism
-> anti-violence -> anarcho-pacifism
-> individualism -> individualist anarchism
-> individualism -> private property -> wages according to labor -> free market -> boston anarchism
-> individualism -> violence -> no natural rights -> obtain property through might -> egoism
-> violence -> class conflict -> informal organization -> insurrectionary anarchism
-> violence -> abolition of work -> anti-ideology -> anti-morality -> post-left anarchism
-> anti-patriarchy -> anarcha-feminism
-> environmental protection -> green anarchism
-> environmental protection -> animal liberation -> veganarchism
-> environmental protection -> collectivism -> eco-villages -> eco-anarchism
-> environmental protection -> collectivism -> abandon all technology -> anarcho-primitivism
-> collectivism -> mutual aid -> socialist anarchism
-> collectivism -> mutual aid -> abolish wages -> labor movement -> anarcho-syndicalism
-> collectivism -> mutual aid -> marxist -> abolish wages -> communes -> no private property -> anarcho-communism
-> collectivism -> mutual aid -> marxist -> wages according to time contribution -> collectively owned property -> collectivist anarchism
*** mutualism
- Mutualist anarchism is concerned with reciprocity, free association, voluntary contract, federation, and credit and currency reform
- The primary aspects of mutualism are free association, mutualist credit, contract (or federation/confederation), and gradualism (or dual-power). Mutualism is often described by its proponents as advocating an "anti-capitalist free market".
- a market without government intervention drives prices down to labor-costs, eliminating profit, rent, and interest according to the labor theory of value
- Firms would be forced to compete over workers just as workers compete over firms, raising wages
- a society where each person might possess a means of production, either individually or collectively, with trade representing equivalent amounts of labor in the free market
- Integral to the scheme was the establishment of a mutual-credit bank which would lend to producers at a minimal interest rate only high enough to cover the costs of administration
- based on a labor theory of value which holds that when labour or its product is sold, in exchange, it ought to receive goods or services embodying "the amount of labor necessary to produce an article of exactly similar and equal utility"
- oppose the idea of individuals receiving an income through loans, investments, and rent, as they believe these individuals are not labouring
- Insofar as they ensure the workers right to the full product of their labor, mutualists support markets and private property in the product of labor. However, they argue for conditional titles to land, whose private ownership is legitimate only so long as it remains in use or occupation (which Proudhon called "possession.")
- Proudhon's Mutualism supports labor-owned cooperative firms and associations for "we need not hesitate, for we have no choice. . . it is necessary to form an ASSOCIATION among workers . . . because without that, they would remain related as subordinates and superiors, and there would ensue two . . . castes of masters and wage-workers, which is repugnant to a free and democratic society" and so "it becomes necessary for the workers to form themselves into democratic societies, with equal conditions for all members, on pain of a relapse into feudalism.
- As for capital goods (man-made, non-land, "means of production"), mutualist opinion differs on whether these should be commonly managed public assets or private property.
- some mutualists have abandoned the labor theory of value, and prefer to avoid the term "socialist."
- Over matters which are purely personal, as for example, moral conduct, the individual is sovereign, as well as over that which he himself produces
- "mutuality" in marriage – the equal right of a woman to her own personal freedom and property" and feminist and spiritualist tendencies.
- Proudhon opposed government privilege that protects capitalist, banking and land interests, and the accumulation or acquisition of property (and any form of coercion  that led to it) which he believed hampers competition and concentrates wealth. 
- Proudhon favored the right of individuals to retain the product of their labor as their own property, but believed that all other property was illegitimate. Thus, he saw private property as both essential to liberty and a road to tyranny, the former when it resulted from labor and was required for labor and the latter when it resulted in/from exploitation (profit, interest, rent, tax). He generally termed the former "possession" and the latter "property." For large-scale industry, he supported workers associations to replace wage labor and opposed land ownership.
- Proudhon maintained that workers should retain the entirety of what they produce, and that monopolies on credit and land are the forces that prohibit this. He advocated an economic system he called mutualism that included possession and exchange of private property but without profit.
- Proudhon originated mutualism, an anarchist school of thought, envisioning a society where each person might possess a means of production, either individually or collectively, with trade representing equivalent amounts of labor in the free market. Integral to the scheme was the establishment of a mutual-credit bank which would lend to producers at an interest rate only high enough to cover the costs of administration.
- Mutualism is based on a labor theory of value  which holds that when labor or its product is sold, in exchange, it ought to receive goods or services embodying "the amount of labor necessary to produce an article of exactly similar and equal utility".
- Insofar as they ensure workers' rights to the full product of their labor, mutualists support markets and private property. However, they argue for conditional title to land, whose private ownership is legitimate only so long as it remains in use or occupation (which Proudhon called "possession.") Proudhon's Mutualism supports labor-owned cooperative firms and associations
- Mutualist opinions differs on whether capital goods (man-made, non-land, "means of production)" should be commonly managed public assets or private property.
- "some mutualists have abandoned the labor theory of value, and prefer to avoid the term "socialist." But they still retain some cultural attitudes, for the most part, that set them off from the libertarian right."(from the Mutualist FAQ - are mutualists socialists? - might be worth checking out)
- Although mutualism is similar to the economic doctrines of the 19th-century American individualist anarchists, unlike them, mutualism is in favor of large industries. Therefore, mutualism has been retrospectively characterized sometimes as being a form of individualist anarchism, and as ideologically situated between individualist and collectivist forms of anarchism as well. Proudhon himself described the "liberty" he pursued as "the synthesis of communism and property."
- Mutualists have distinguished mutualism from state socialism, and do not advocate state control over the means of production.
- Mutualists argue that most of the economic problems associated with capitalism each amount to a violation of the cost principle, or as Josiah Warren interchangeably said, "Cost the limit of price." It was inspired by the labor theory of value, which was popularized, though not invented, by Adam Smith in 1776 (Proudhon mentioned Smith as an inspiration). The labor theory of value holds that the actual price of a thing (or the "true cost") is the amount of labor that was undertaken to produce it. In Warren's terms, cost should be the "limit of price," with "cost" referring to the amount of labor required to produce a good or service. Anyone who sells goods should charge no more than the cost to himself of acquiring these goods.
- generally considered a market-oriented strand within the libertarian socialist tradition
- typically accept property rights, but with brief abandonment time periods
*** social anarchism
*** collectivist anarchism
- revolutionary
- sees individual freedom as conceptually connected with social equality and emphasize community and mutual aid
- unlike mutualists, collectivist anarchists oppose all private ownership of the means of production, instead advocating that ownership be collectivized
- to be initiated by small cohesive elite group through acts of violence, or "propaganda by the deed," which would inspire the workers to revolt and forcibly collectivize the means of production
- Workers would be compensated for their work on the basis of the amount of time they contributed to production, rather than goods being distributed "according to need" as in anarcho-communism
- collectivist anarchists advocated compensation for labor, some held out the possibility of a post-revolutionary transition to a communist system of distribution according to need
- opposed the Marxist dictatorship of the proletariat, despite Marxism striving for a collectivist stateless society
- Some collectivist anarchists do not oppose the use of currency
- These salaries would be used to purchase commodities in a communal market
- contrasts with anarcho-communism where wages would be abolished, and where individuals would take freely from a storehouse of goods "to each according to his need"
- Many modern-day collectivist anarchists hold their form of anarchism as a permanent society rather than a carryover to anarcho-communism or a gift economy
- Some collectivist anarchists such as proponents of participatory economics believe in remuneration and a form of credit but do not believe in money or markets
- collectivist anarchists believe that the economy and most or all property should be collectively owned by society while anarchist communists by contrast believe that the concept of ownership should be rejected by society and replaced with the concept of usage
- Collectivist anarchists often favor using a form of currency to compensate workers according to the amount of time spent contributing to society and production while Anarcho-communists believe that currency and wages should be abolished all together and goods should be distributed "to each according to his or her need"
- saw their economic order as evolving into free communism
- At this time (the 1880s), the anarcho-communists stressed local cells of anarchist militants, generally opposed trade unionism as were characterized by a degree of anti-organisation
*** anarchist communism / anarcho-communism
- advocates the abolition of the state, markets, money, private property (while retaining respect for personal property), and capitalism in favor of common ownership of the means of production,[34][35] direct democracy and a horizontal network of voluntary associations and workers' councils  with production and consumption based on the guiding principle: "from each according to his ability, to each according to his need"
- Some forms of anarchist communism such as insurrectionary anarchism are strongly influenced by egoism and radical individualism, believing anarcho-communism is the best social system for the realization of individual freedom
- Most anarcho-communists view anarcho-communism as a way of reconciling the opposition between the individual and society
- It is Proudhon's philosophy that was explicitly rejected by Joseph Dejacque in the inception of anarchist-communism, with the latter asserting directly to Proudhon in a letter that "it is not the product of his or her labour that the worker has a right to, but to the satisfaction of his or her needs, whatever may be their nature."
- Some forms of anarchist communism, such as insurrectionary anarchism, are strongly influenced by egoism and radical individualism, believing anarcho-communism is the best social system for the realization of individual freedom. Some anarcho-communists view anarcho-communism as a way of reconciling the opposition between the individual and society.
- Anarchist communists argue that there is no valid way of measuring the value of any one person's economic contributions because all wealth is a collective product of current and preceding generations.
- Anarchist communists argue that any economic system based on wage labor and private property requires a coercive state apparatus to enforce property rights and to maintain unequal economic relationships that inevitably arise from differences in wages or amount of property
- they further argue that markets and systems of currency divide labor into classes and assign arbitrary numerical values to an individual's work and attempt to regulate production, consumption and distribution. They argue that money restricts an individual's ability to consume the products of their labor by limiting their intake with prices and wages
- Communist anarchism shares many traits with collectivist anarchism, but the two are distinct. Collectivist anarchism believes in collective ownership while communist anarchism negates the entire concept of ownership in favor of the concept of usage. Thus, things are seen as either private possessions used by an individual, or social possessions used to produce for society. Anarcho-communists believe that means of production should not be owned by any one person or entity, leaving it free to be used by individuals for their own self-determined needs and wants. Land and housing would no longer be subject to rent or property taxes (and therefore, its use would be free of eviction threats)
- Anarcho-communists reject mutualist economics because they believe that market competition, even non-capitalist markets, inherently create inequalities in wealth and land which would lead to inequalities of power—thus the recreation of the State and capitalism as some workers would have more access to capital and defence force than others
- They reject collectivist economics arguing that remuneration would require a type of currency, which, again, anarcho-communists reject as an artificial measurement of the value of labor
- further argue that those who are not part of collective groups or unions in workers' councils and collectives could be alienated from access to capital, and thus promote free common use over ownership by society
*** pro-organizationalist anarcho-communism
*** anti-organizationalist / insurrectionary anarcho-communism
https://en.wikipedia.org/wiki/Insurrectionary_anarchism
*** anarcho-syndicalism
- posits radical trade unions as a potential force for revolutionary social change, replacing capitalism and the state with a new society, democratically self-managed by the workers
- seek to abolish the wage system and private ownership of the means of production, which they believe lead to class divisions
- Important principles of syndicalism include workers' solidarity, direct action (such as general strikes and workplace recuperations), and workers' self-management
- anarcho-syndicalists often subscribe to communist or collectivist anarchism
- propose labour organization as a means to create the foundations of a non-hierarchical anarchist society within the current system and bring about social revolution
- anarcho-syndicalist economic systems often take the form of either a collectivist anarchist economic system or an anarcho-communist economic system
*** individualist anarchism
- Individualist anarchism refers to several traditions of thought within the anarchist movement that emphasize the individual and his or her will over external determinants such as groups, society, traditions, and ideological systems
- emphasize personal autonomy and the rational nature of human beings
- emphasizes the individual and their will over any kinds of external determinants such as groups, society, traditions, and ideological systems
- The great majority of Americans during this time were farmers working their own land, primarily for their own needs." and so "Individualist anarchism is clearly a form of artisanal socialism ... while communist anarchism and anarcho-syndicalism are forms of industrial (or proletarian) socialism.
- The concentration on the individual and their will in preference to any construction such as morality, ideology, social custom, religion, metaphysics, ideas or the will of others
- rejection of or reservations about the idea of revolution, seeing it as a time of mass uprising which could bring about new hierarchies. Instead they favor more evolutionary methods of bringing about anarchy through alternative experiences and experiments and education which could be brought about today
- view that relationships with other persons or things can be in one's own interest only and can be as transitory and without compromises as desired since in individualist anarchism sacrifice is usually rejected. In this way, Max Stirner recommended associations of egoists. Individual experience and exploration therefore is emphasized.
- Another important tendency within individualist anarchist currents emphasizes individual subjective exploration and defiance of social conventions.
- individualist anarchism remained largely a bohemian lifestyle, most conspicuous in its demands for sexual freedom ('free love') and enamored of innovations in art, behavior, and clothing.". In this way free love currents and other radical lifestyles such as naturismhad popularity among individualist anarchists
- individualist anarchism "under its iconoclastic, antiintelectual, antitheist run, which goes against all sacralized ideas or values it entailed, a philosophy of life which could be considered a reaction against the sacred gods of capitalist society. Against the idea of nation, it opposed its internationalism. Against the exaltation of authority embodied in the military institution, it opposed its antimilitarism. Against the concept of industrial civilization, it opposed its naturist vision"
- On the issue of violence opinions have gone from a violentist point of view mainly exemplified by illegalism and insurrectionary anarchism to one that can be called anarcho-pacifis
- godwinian individualist anarchism - actually believed in a utilitarian gift economy? and some other weird stuff
- proudhonian anarchism - favoured a right of individuals to retain the product of their labour as their own property, but believed that any property beyond that which an individual produced and could possess was illegitimate. Thus, he saw private property as both essential to liberty and a road to tyranny, the former when it resulted from labour and was required for labour and the latter when it resulted in exploitation (profit, interest, rent, tax). He generally called the former "possession" and the latter "property."
- viewed sexual freedom as a clear, direct expression of an individual's self-ownership
- Free love particularly stressed women's rights since most sexual laws, such as those governing marriage and use of birth control, discriminated against women.
- free love, freethrought (anti-Christian, anti-clerical movement, whose purpose was to make the individual politically and spiritually free to decide for himself on religious matters), anarcho-naturism
- Naturist individualist anarchists saw the individual in his biological, physical and psychological aspects and avoided, and tried to eliminate, social determinations
- 19th century individualist anarchists espoused the labor theory of value
-  Bookchin claimed that individualist anarchism supports only negative liberty and rejects the idea of positive liberty
- Michael Freeden identifies four broad types of individualist anarchism. He says the first is the type associated with William Godwin that advocates self-government with a "progressive rationalism that included benevolence to others." The second type is the amoral self-serving rationality of Egoism, as most associated with Max Stirner. The third type is "found in Herbert Spencer's early predictions, and in that of some of his disciples such as Donisthorpe, foreseeing the redundancy of the state in the source of social evolution." The fourth type retains a moderated form of egoism and accounts for social cooperation through the advocacy of market relationships.
*** american individualist anarchism
- (Kevin Carson on american individualist anarchism) Unlike the rest of the socialist  movement, the individualist anarchists believed that the natural wage of labor in a free market was its product, and that economic exploitation could only take place when capitalists and landlords harnessed the power of the state in their interests. Thus, individualist anarchism was an alternative both to the increasing statism of the mainstream socialist movement, and to a classical liberal movement that was moving toward a mere apologetic for the power of big business
- josiah warren - 'cost the limit of price' / time store
- anarchist individualists "are firm in the idea that the system of employer and employed, buying and selling, banking, and all the other essential institutions of Commercialism, centred upon private property, are in themselves good, and are rendered vicious merely by the interference of the State."
- American individualists had no difficulty accepting the concepts that "one man employ another" or that "he direct him," in his labor but rather demanded that "all natural opportunities requisite to the production of wealth be accessible to all on equal terms and that monopolies arising from special privileges created by law be abolished."
- disagreed amongst each other on various issues including intellectual property rights and possession versus property in land
- American individualist anarchists accept that free competition results in unequal wealth distribution, but they "do not see that as an injustice."
- American individualist anarchism "stresses the isolation of the individual – his right to his own tools, his mind, his body, and to the products of his labor.
*** european individualist anarchism
- In European individualist anarchism a different social context helped the rise of European individualist illegalism and as such "The illegalists were proletarians who had nothing to sell but their labour power, and nothing to discard but their dignity; if they disdained waged-work, it was because of its compulsive nature. If they turned to illegality it was due to the fact that honest toil only benefited the employers and often entailed a complete loss of dignity, while any complaints resulted in the sack; to avoid starvation through lack of work it was necessary to beg or steal, and to avoid conscription into the army many of them had to go on the run."
- And so a European tendency of individualist anarchism advocated violent individual acts of individual reclamation, propaganda by the deed and criticism of organization. Such individualist anarchist tendencies include French illegalism and Italian anti-organizational insurrectionarism
- French individualist anarchism was characterized by an eclectic set of currents of thought and practices which included freethought, naturism, free love, anti-militarism and illegalism.
- bellegarrigue - getting some whiffs of objectivism - "I deny everything; I affirm only myself.... I am, that is a positive fact. All the rest is abstract and falls into Mathematical X, into the unknown.... There can be on earth no interest superior to mine, no interest to which I owe even the partial sacrifice of my interests." Yet in apparent contradiction, Bellegarrigue adhered to the central anarchist tradition in his idea of society as necessary and natural and as having "a primordial existence"
- French individualist anarchists espoused diverse positions. For example, Emile Armand rejected violence and embraced mutualism while advocating free love. Albert Libertad and Zo d'Axa championed violent propaganda by the deed  while adhering to communitarianism or anarcho-communism and rejecting work. Han Ryner on the other side conciled anarchism with stoicism. Nevertheless, French individualist circles displayed a strong sense of personal libertarianism and experimentation. Anarchist naturism and free love concepts influenced individualist anarchists circles in France and Spain and expanded to the rest of anarchism.
- Freethought as a philosophical position and as activism was important in french individualist anarchism. 
- Emile Armand was an influential French individualist anarchist, free love/polyamory and pacifist/antimilitarist propagandist and activist.
- Armand contrasted his IA with social anarchist currents, rejecting revolution. He argued that waiting for revolution meant delaying the enjoyment of liberty until the masses gained awareness and will. Instead he advocated living under one's own conditions in the present time, revolting against social conditioning in daily life and living with those with an affinity to oneself in accord to the values and desire they share. He says the individualist is a "presentist" and "he could not, without bad reasoning and illogic, think of sacrificing his being, or his having, to the coming of a state of things he will not immediately enjoy". He applies this rule to friendship, love, sexual encounters and economic transactions. He adheres to an ethics of reciprocity and advocated propagandizing one's values to enable association with others to improve the chances of self-realization
- Charles-Auguste Bontemps - was a prolific author mainly in the anarchist, freethinking, pacifist and naturist press of the time. His view on anarchism was based around his concept of "Social Individualism" on which he wrote extensively. He defended an anarchist perspective which consisted on "a collectivism of things and an individualism of persons."
- Federico Urales was an important catalan individualist anarchist who edited La Revista Blanca. The individualist anarchism of Urales was influenced by Auguste Comte and Charles Darwin. He saw science and reason as a defense against blind servitude to authority. He was critical of influential individualist thinkers such as Nietzsche and Stirner for promoting an asocial egoist individualism and instead promoted an individualism with solidarity as a way to guarantee social equality and harmony. In the subject of organization he was highly critical of anarcho-syndicalism as he saw it plagued by too much bureaucracy and thought that it tended towards reformism. Instead he favored small groups based on ideological alignement
*** egoist anarchism
- rejects devotion to "a great idea, a cause, a doctrine, a system, a lofty calling"
- has no political calling but rather "lives themselves out" without regard to "how well or ill humanity may fare thereby"
- the only limitation on the rights of the individual is his power to obtain what he desires
- most commonly accepted social institutions – including the notion of State, property as a right, natural rights in general, and the very notion of society – were mere spooks in the mind
- 
- wanted to "abolish not only the state but also society as an institution responsible for its members"
- "union of egoists"
- concept of "egoistic property" not only rejects moral restraint on how one obtains and uses things, but includes other people as well
- (benjamin tucker) Tucker said that there were only two rights, "the right of might" and "the right of contract"
- Tucker rejected natural rights which had long been considered the foundation of libertarianism
- (james walker) egosim "implies a rethinking of the self-other relationship, nothing less than "a complete revolution in the relations of mankind" that avoids both the "archist" principle that legitimates domination and the "moralist" notion that elevates self-renunciation to a virtue
- Walker describes himself as an "egoistic anarchist" who believed in both contract and cooperation as practical principles to guide everyday interactions."
- For Walker the egoist rejects notions of duty and is indifferent to the hardships of the oppressed whose consent to their oppression enslaves not only them, but those who do not consent.
- The egoist comes to self-consciousness, not for the God's sake, not for humanity's sake, but for his or her own sake.
- Cooperation and reciprocity are possible only among those who are unwilling to appeal to fixed patterns of justice in human relationships and instead focus on a form of reciprocity, a union of egoists, in which person each finds pleasure and fulfillment in doing things for others
- what really defines egoism is not mere self-interest, pleasure, or greed; it is the sovereignty of the individual, the full expression of the subjectivity of the individual ego
- "private property is a spook which "lives by the grace of law" and it "becomes 'mine' only by effect of the law"
*** boston anarchists
- 
*** illegalism
- openly embraced criminality as a lifestyle
- found justification in Stirner's philosophy
- usually did not seek moral basis for their actions, recognizing only the reality of "might" rather than "right"
- illegal acts were done simply to satisfy personal desires and needs, not for some greater ideal, although some committed crimes as a form of propaganda of the deed
- The illegalists embraced direct action and propaganda of the deed.
- The illegalists broke from anarchists like Clément Duval and Marius Jacob who justified theft with a theory of la reprise individuelle (individual reclamation). Instead, the illegalists argued that their actions required no moral basis; illegal acts were performed not in the name of a higher ideal, but in pursuit of one's own desires
- an outgrowth of Stirner's Individualist anarchism
- Influenced by Stirner's egoism as well as Proudhon's "property is theft", Clément Duval and Marius Jacob proposed the theory of individual reclamation.
- broke from anarchists like Clément Duval and Marius Jacob who justified theft with a theory of la reprise individuelle (Eng: individual reclamation). Instead, the illegalists argued that their actions required no moral basis - illegal acts were taken not in the name of a higher ideal, but in pursuit of one's own desires
*** agorism
- Agorism was developed from anarcho-capitalism in the late 20th century
- Agorists are market anarchists
- The goal of agorists is a society in which all "relations between people are voluntary exchanges – a free market."
- Most Agorists consider that property rights are natural rights deriving from the primary right of self-ownership
- not opposed in principle to collectively held property if individual owners of the property consent to collective ownership by contract or other voluntary mutual agreement.
- Agorists are divided on the question of intellectual property rights
*** existentialist anarchism
- David Goodway writes "Here we have the egoism of Max Stirner assimilated in the anarchist communism of Peter Kropotkin
- Some observers believe existentialism forms a philosophical ground for anarchism
- there is a close link between the existentialists' stress on the individual, free choice, and moral responsibility and the main tenets of anarchism
- 
*** religious anarchism
- many anarchists have traditionally been skeptical of and opposed to organized religion
- Christian anarchists believe that biblical teachings give credence to anarchist philosophy
*** anarcho-pacifism
- completely rejects the use of violence in any form for any purpose
- advocacy of nonviolent resistance
- rejects propaganda by the deed
- anarchism must by nature be nonviolent since it is, by definition, opposition to coercion and force
- since the state is inherently violent, meaningful pacifism must likewise be anarchistic
*** anarchism without adjectives
- refers to an unhyphenated form of anarchism, that is, a doctrine without any qualifying labels such as communist, collectivist, mutualist, or individualist
- an attitude that tolerated the coexistence of different anarchist schools
- emphasizes harmony between various anarchist factions and attempts to unite them around their shared anti-authoritarian beliefs
- only different methods of economy, the practical possibilities of which have yet to be tested, and that the first objective is to secure the personal and social freedom of men no matter upon which economics basis this is to be accomplished.
- Socialism and Communism both demand a degree of joint effort and administration which would beget more regulation than is wholly consistent with ideal Anarchism (Voltairine de Cleyre)
- Individualism and Mutualism, resting upon property, involve a development of the private policeman not at all compatible with my notion of freedom (Voltairine de Cleyre)
- There is nothing un-Anarchistic about any of [these systems] until the element of compulsion enters and obliges unwilling persons to remain in a community whose economic arrangements they do not agree to. (Voltairine de Cleyre)
- anarchists should not impose a preconceived economic plan on anyone—even in theory
- tended either to reject all particular anarchist economic models as faulty, or take a pluralist position of embracing them all to a limited degree in order that they may keep one another in check
*** synthesist anarchism
- tries to join anarchists of different tendencies under the principles of anarchism without adjectives
- specifically was trying to join anarcho-syndicalism, libertarian communism, and anarchist individualism
*** green anarchism / eco-anarchism
- school of thought within anarchism which puts an emphasis on environmental issues
*** social ecology
- considered a kind of green anarchist
- considered a kind of socialist anarchist
- present ecological problems  are rooted in deep-seated social problems, particularly in dominatory hierarchical political and social systems. These have resulted in an uncritical acceptance of an overly competitive grow-or-die philosophy
- this cannot be resisted by individual action such as ethical consumerism but must be addressed by more nuanced ethical thinking and collective activity grounded in radical democratic ideals
- The complexity of relationships between people and with nature is emphasised, along with the importance of establishing social structures that take account of this
- often criticize the main currents of anarchism for their focus and debates about politics and economics instead of a focus on eco-system (human and environmental)
- promotes libertarian municipalism and green technology
*** anarcho-primitivists
- often criticize mainstream anarchism for supporting civilization and modern technology which they believe are inherently based on domination and exploitation
- instead advocate the process of rewilding or reconnecting with the natural environment
*** veganarchism
- political philosophy of veganism (more specifically animal liberation) and green anarchism
- encompasses viewing the state as unnecessary and harmful to both human and animals, whilst practising a vegan diet
*** anarcho-naturism
- union of anarchist and naturist philosophies
- mainly it had importance within individualist anarchist circles... why?
- advocated vegetarianism, free love, nudism, small ecovillages, hiking and an ecological world view
- Naturist individualist anarchists saw the individual in his biological, physical and psychological aspects and tried to eliminate social determinations
- By shunning the humble garment of an exploited person, (garments which, in my opinion, are the result of all the laws devised to make our lives bitter), we feel there no others left but just the natural law
- Zisly vividly criticized progress and civilization, which he regarded as 'absurd, ignoble, and filthy.' He openly opposed industrialization, arguing that machines were inherently authoritarian, defended nudism, advocated a non-dogmatic and non-religious adherence to the 'laws of nature,' recommended a lifestyle based on limited needs and self-sufficiency, and disagreed with vegetarianism, which he considered 'anti-scientific.'"
- some vegetarian, some "vegetalian" (vegan), some omnivore
- Naturism promoted an ecological worldview, small ecovillages, and most prominently nudism as a way to avoid the artificiality of the industrial mass society of modernity
*** anarcho-primitivism
- an anarchist critique of the origins and progress of civilization
- the shift from hunter-gatherer to agricultural subsistence gave rise to social stratification, coercion, and alienation
- advocate a return to non-"civilized" ways of life through deindustrialisation, abolition of the division of labour or specialization, and abandonment of large-scale organization technologies
- There are other non-anarchist forms of primitivism, and not all primitivists point to the same phenomenon as the source of modern, civilized problems
- often distinguished by their focus on the praxis of achieving a feral state of being through "rewilding"
- Many traditional anarchists reject the critique of civilization
- random redditor - "Anarcho-Primitivism does not mean "abandon all technology", it's far more nuanced than that, and technology is but one factor relevant to A-P, others including critiques of symbolic culture, domestication, sedentism, surplus, and urbanization. Anarcho-naturism is an older but related current in Green Anarchist thought."
*** anarcha-feminism
- synthesizes radical feminism and anarchism that views patriarchy (male domination over women) as a fundamental manifestation of involuntary hierarchy which anarchists often oppose
- criticize and advocate the abolition of traditional conceptions of family, education and gender roles
- especially critical of marriage
- criticize the views of some of the traditional anarchists such as Mikhail Bakunin who have believed that patriarchy is only a minor problem and is dependent only on the existence of the state and capitalism and will disappear soon after such institutions are abolished. Anarcha-feminists by contrast view patriarchy as a fundamental problem in society and believe that the feminist struggle against sexism and patriarchy is an essential component of the anarchist struggle against the state and capitalism.
*** platformism
- stresses the need for tightly organized anarchist organizations, that are able to influence working class and peasant movements. It is in many ways identical to especifismo, and has an antecedent in the work of Mikhail Bakunin
- reject the model of Leninist vanguardism. They aim, instead, to "make anarchist ideas the leading ideas within the class struggle"
- platformist groups aim to win the widest possible influence for anarchist ideas and methods in the working class and peasantry—like especifismo groups, platformists orient towards "ordinary" people, rather than to the extreme left milieu
- usually entailing a willingness to work in single-issue campaigns, trade unionism and community groups, and to fight for immediate reforms while linking this to a project of building popular consciousness and organisation. They therefore reject approaches that they believe will prevent this, such as insurrectionist anarchism, as well as "views that dismiss activity in the unions" or that dismiss anti-imperialist movements
*** anarcho-queer
- suggests anarchism as a solution to the issues faced by the LGBT community, mainly heteronormativity, homophobia, transphobia and biphobia
*** post-left anarchism
- promotes a critique of anarchism's relationship to traditional leftism
- seek to escape the confines of ideology in general also presenting a critique of organizations and morality
- Influenced by the work of Max Stirner and by the Situationist International, post-left anarchy is marked by a focus on social insurrection and a rejection of leftist social organisation
- influenced profoundly by egoism in aspects such as the critique of ideology
- a shift among Euro-American anarchists away from social anarchism and toward individualist or lifestyle anarchism. Indeed, lifestyle anarchism today is finding its principal expression in spray-can graffiti, post-modernist nihilism, antirationalism, neo-primitivism, anti-technologism, neo-Situationist 'cultural terrorism', mysticism, and a 'practice' of staging Foucauldian 'personal insurrections'."
- (According to Bob Black) - "It is, unlike Bookchinism, "individualistic" in the sense that if the freedom and happiness of the individual – i.e., each and every really existing person, every Tom, Dick and Murray – is not the measure of the good society, what is?"
- some random person on reddit - "the anti-ideology and anti-morality pillars of post-left anarchism originate in egoism"
*** post-anarchism
- hybrid of post-structuralism and anarchism
- Like existentialism, these approaches reject essentialist or reductionist notions, and are critical of dominant Western philosophy and culture, rejecting previous systems of knowledge based on the human knower. Since the 1980s, therefore, a growing number of anarchist philosophies, represented by the term "post-anarchism," have used post-structuralist and postmodernist approaches
- Saul Newman has utilized prominently Max Stirner and Friedrich Nietzsche along with such thinkers as Jacques Lacan in his post-anarchist works. Newman criticizes classical anarchists for assuming an objective "human nature" and a natural order
- She believes anarchism is a philosophy based on "existential individualism" that emphasizes the freedom of the individual, and defines "existential individualism" as the belief in freedom for freedom's sake, as opposed to "instrumental individualism," which more often exists in liberal works and is defined as freedom to satisfy individual interests without a meaningful belief in freedom. But she argues, like post-anarchists, that classical anarchist theory has asserted human beings as naturally cooperative, and that this fixed human nature presents many problems for anarchism as it contradicts its commitment to free will and the individual. For anarchism to be fundamentally individualist, she argues, it must look to existentialism for a more "fluid conceptualization of human nature."
*** insurrectionary anarchism
- apparently a form of individualist anarchism
- emphasizes the theme of insurrection (revolution, rebellion, uprising) within anarchist practice
- opposes formal organizations such as labor unions and federations that are based on a political programme and periodic congresses.
- support informal organization and small affinity group based organization
- put value in attack, permanent class conflict, and a refusal to negotiate or compromise with class enemies
- Contemporary insurrectionary anarchism inherits the views and tactics of anti-organizational anarcho-communism and illegalism
- Egoism has had a strong influence on insurrectionary anarchism
- In the game of insurgence—a lived guerilla war game—it is strategically necessary to use identities and roles. Unfortunately, the context of social relationships gives these roles and identities the power to define the individual who attempts to use them. So I, Feral Faun, became ... an anarchist ... a writer ... a Stirner-influenced, post-situationist, anti-civilization theorist ... if not in my own eyes, at least in the eyes of most people who've read my writings
- The workers who, during a wildcat strike, carried a banner saying, 'We are not asking for anything' understood that the defeat is in the claim itself ('the claim against the enemy is eternal'). There is no alternative but to take everything. As Stirner said: 'No matter how much you give them, they will always ask for more, because what they want is no less than the end of every concession'
- it is the risen people who are the real agent and not the working class organised in the enterprise (the cells of the capitalist mode of production) and seeking to assert itself as labour power, as a more 'rational' industrial body or social brain (manager) than the employers
- So "between 1880 and 1890" with the "perspective of an immanent revolution", who was "opposed to the official workers' movement, which was then in the process of formation (general Social Democratisation). They were opposed not only to political (statist) struggles but also to strikes which put forward wage or other claims, or which were organised by trade unions." But "While they were not opposed to strikes as such, they were opposed to trade unions and the struggle for the eight-hour day. This anti-reformist tendency was accompanied by an anti-organisational tendency, and its partisans declared themselves in favour of agitation amongst the unemployed for the expropriation of foodstuffs and other articles, for the expropriatory strike and, in some cases, for 'individual recuperation' or acts of terrorism."
- contemporary insurrectionary anarchism - "attack" rather than mediation, pacification, sacrifice, accomodation, or compromise; revolution as a "concrete event"; self-management of struggle; temporary affinity groups instead of permanent organizations; transcendence of dichotomy between the individual and the rest of society
- "Insurrection begins with the desire of individuals to break out of constrained and controlled circumstances, the desire to reappropriate the capacity to create one's own life as one sees fit." But the view that "Individuality can only flourish where equality of access to the conditions of existence is the social reality. This equality of access is communism; what individuals do with that access is up to them and those around them. Thus there is no equality or identity of individuals implied in true communism.
*** left-wing market anarchism
- stress the value of radically free markets, termed freed markets to distinguish them from the common conception which these libertarians believe to be riddled with statist and capitalist privileges
- strongly affirm the classical liberal ideas of self-ownership and free markets, while maintaining that, taken to their logical conclusions, these ideas support strongly anti-corporatist, anti-hierarchical, pro-labor positions in economics; anti-imperialism in foreign policy; and thoroughly liberal or radical views regarding such cultural issues as gender, sexuality, and race
- tends to be rooted either in the mutualist economics conceptualized by Pierre-Joseph Proudhon, American individualist anarchism, or in a left-wing interpretation or extension of the thought of Murray Rothbard
- a form of left-libertarianism, individualist anarchism, and libertarian socialism
- stress both individual freedom and social justice
- Unlike right-libertarians, they believe that neither claiming nor mixing one's labor with natural resources is enough to generate full private property rights, and maintain that natural resources (land, oil, gold, trees) ought to be held in some egalitarian  manner, either unowned or owned collectivel
- Those left-libertarians who support private property do so under the condition that recompense is offered to the local community.
*** anarcho-capitalism
- advocates the elimination of the state in favour of individual sovereignty in a free market
- developed from radical anti-state libertarianism and individualist anarchism, drawing from Austrian School economics, study of law and economics, and public choice theory
- There is a strong current within anarchism which does not believe that anarcho-capitalism can be considered to be a part of the anarchist movement due to the fact that anarchism has historically been an anti-capitalist movement and for definitional reasons which see anarchism as incompatible with capitalism
- some believe that the modern movement of anarcho-capitalism is the result of simply removing the labor theory of value from ideas of the 19th-century American individualist anarchists
- As economic theory changed, the popularity of the labor theory of classical economics was superseded by the subjective theory of value of neo-classical economics
-  Murray Rothbard, a student of Ludwig von Mises, combined the Austrian school economics of his teacher with the absolutist views of human rights and rejection of the state he had absorbed from studying the individualist American anarchists of the 19th century
- In the mid-1950s Rothbard wrote an article under a pseudonym, saying that "we are not anarchists ... but not archists either ... Perhaps, then, we could call ourselves by a new name: nonarchist - LOL
*** anarcho-transhumanism
- takes traditional and modern anarchism, typically anarcho-syndicalism and combines it with transhumanism and post-humanism
- described as a liberal democratic revolution, at its core the idea that people are happiest when they have rational control over their lives. Reason, science, and technology provide one kind of control, slowly freeing us from ignorance, toil, pain, disease and limited lifespans (aging)
*** contemporary anarchism
- Anarchism is a political philosophy which holds the state to be undesirable, unnecessary, or harmful. However, others argue that while anti-statism is central, it is inadequate to define anarchism solely on this basis. Therefore, they argue instead that anarchism entails opposing authority or hierarchical organization in the conduct of human relations, including, but not limited to, the state system.
- Proponents of this form of anarchism advocate stateless societies based on non-hierarchical free associations
- "There is no doubt that 60s anarchism was libertarian and linked to the sexual revolution, liberation of the erotic instincts and what Herbert Marcuse called "nonrepressive sublimation". Yet, contemporary anarchism can be seen as a powerful critique of the pseudo-libertarianism of contemporary neo-liberalism, where the sexual revolution has turned the culture industry into the sex industry - ask yourself, is there today anything less transgressive and more normalizing than pornography? One might say that contemporary anarchism is about responsibility, whether sexual, ecological or socio-economic; it flows from an experience of conscience about the manifold ways in which the West ravages the rest; it is an ethical outrage at the yawning inequality, impoverishment and disenfranchisment that is so palpable locally and globally."
- grew in popularity and influence as part of the anti-war, anti-capitalist, and anti-globalisation movements
*** freiwirtschaft ("free economy")
why is this anarchism?
- All money is issued for a limited period by constant value; Long-term saving requires investment in bonds or stocks
- All land is commonly owned or else the property of public institutions and can only be rented from the community or from government, respectively, not purchased (similar to Georgism?)
- free trade
*** inclusive democracy
- direct democracy; economic democracy in a stateless, moneyless and marketless economy; self-management (democracy in the social realm); and ecological democracy
- 'democratic planning' of the economy
- meant to offer an alternative to neoliberalism and existing forms of socialism (i.e. neither market economy nor state planning)
- is not openly anarchism, yet anarchism seems the formal category within which he works, given his commitment to direct democracy, municipalism and abolition of state, money and market economy
- synthesis of classical democracy and socialist, although it also encompasses radical green, feminist, and liberation movements in the South
- the world, at the beginning of the new millennium, faces a multi-dimensional crisis (economic, ecological, social, cultural and political), which is shown to be caused by the concentration of power in the hands of various elites. This is interpreted to be the outcome of the establishment, in the last few centuries, of the system of market economy (in the Polanyian sense), Representative democracy, and the related forms of hierarchical structure. Therefore, an inclusive democracy is seen not simply as a utopia, but perhaps as the only way out of the crisis, based on the equal distribution of power at all levels.
- federations of "demoi", units of ~30k people
- equal political, economic, ... power
- community controls the means of production
- mentions that this is different from "collectivist capitalism" like worker's control
- macroeconomic decisions made by community, microeconomic made by individuals in an "artificial market" via labor vouchers (which cannot be used as a general medium of exchange or store wealth) (apparently this is similar to mutualism)
- requires demotic self-reliance, demotic ownership of the means of production, and confederal allocation of resources
- key difference from parecon - whole community makes economic decisions rather than vocationally-oriented groups
- distinguishes between basic and non-basic needs - renumeration according to need for basic needs, according to effort for non-basic needs
- reject the traditional socialist adoption of the labour theory of value as they believe it cannot be used as the basis for allocating scarce resources. The reason given is that even if the labour theory of value can give a (partial) indication of availability of resources, it certainly cannot be used as a means to express consumers’ preferences
- wikipedia article isn't super clear... maybe come back to it
*** anarchist economics
see the wiki article... lots of "methods" to include
- classical: mutualism, collectivist anarchism, anarchist communism
- post-classical: parecon, inclusive democracy, left-wing market anarchism, ancap
- wage slavery
- alternate currencies
- gift economy
- theories of value
- economic pluralism
- economic democracy
*** religious anarchism
- human rulers are illegitimate
*** anarcha-feminism
- views patriarchy as a manifestation of involuntary coercive hierarchy, that should be replaced by decentralized free association
- the struggle against patriarchy is an essential part of class conflict and the anarchist struggle against the state
- In essence, the philosophy sees anarchist struggle as a necessary component of feminist struggle and vice versa
- anti-authoritarian, anti-capitalist, anti-oppressive philosophy, with the goal of creating an "equal ground" between males and females
- suggests the social freedom and liberty of women, without needed dependence upon other groups or parties
- free love (at in early forms)
- proletarian women were exploited not only by capitalism like male workers, but also by their male counterparts
- opposition to traditional concepts of family, education and gender roles
*** anarcho-syndicalism
- views revolutionary industrial unionism or syndicalism as a method for workers in capitalist society to gain control of an economy and, with that control, influence broader society
- The basic principles of anarcho-syndicalism are solidarity, direct action  (action undertaken without the intervention of third parties such as politicians, bureaucrats, and arbitrators) and direct democracy, or workers' self-management. The end goal of anarcho-syndicalism is to abolish the wage system, regarding it as wage slavery. Anarcho-syndicalist theory therefore generally focuses on the labour movement
- In contrast with other bodies of thought, particularly with Marxism–Leninism, anarcho-syndicalists accept the denial of a workers' state, or a state which acts in the interests of workers, as opposed to those of the powerful, and posit that any state with the intention of empowering the workers will inevitably work to empower itself or the existing elite at the expense of the workers
- Reflecting the anarchist philosophy from which it draws its primary inspiration, anarcho-syndicalism is centred around the idea that power corrupts
- direct action
- With greater focus on the labour movement than previous forms of anarchism, syndicalism posits radical trade unions as a potential force for revolutionary social change, replacing capitalism and the state with a new society, democratically self-managed by the workers
- less a type of social anarchism than a set of strategies for achieving either collectivist anarchism or communist anarchism; or first the former, then the latter, once a certain degree of technical-productive capacity has enabled production to outstrip consumption, making a moneyless economy more viable
*** collectivist anarchism
- revolutionary anarchist doctrine that advocates the abolition of both the state and private ownership of the means of production
- instead envisions the means of production being owned collectively and controlled and managed by the producers themselves
- salaries set democratically, then used to purchase goods in a communal market - in constrast with anarcho-communism where wages would be abolished, and where individuals would take freely from a storehouse of goods "to each according to his need." (so, despite title, more of a blen od individualism and collectivism)
- The difference between collectivist anarchism and anarchist communism is that under the former, a wage system is retained based on the amount of labor performed. Anarchist communism, like collectivist anarchism, also advocates for the socialization of production, but the distribution of goods as well. Instead of 'to each according to his labor', in anarcho-communism the community would supply the subsistence requirements to each member free of charge according to the maxim 'to each according to his needs'
- a specific tendency, not to be confused with the broad category sometimes called collectivist or communitarian anarchism
- Unlike mutualists, collectivist anarchists oppose all private ownership of the means of production, instead advocating that ownership be collectivized. This was to be achieved through violent revolution, first starting with a small cohesive group through acts of violence, or "propaganda by the deed," which would inspire the workers as a whole to revolt and forcibly collectivize the means of production. However, collectivization was not to be extended to the distribution of income, as workers would be paid according to time worked, rather than receiving goods being distributed "according to need" as in anarcho-communism. This position was criticised by later anarcho-communists as effectively "uphold[ing] the wages system"
- Collectivist anarchism arose contemporaneously with Marxism but opposed the Marxist dictatorship of the proletariat, despite the stated Marxist goal of a collectivist stateless society.
*** social anarchism
- non-state form of socialism
- sees individual freedom as being dependent upon mutual aid
- emphasizes community and social equality as complementary to autonomy and personal freedom
- advocate the conversion of present-day private property  into social property or the commons, while retaining respect for personal property
- term is used to describe those who—contra anarchist individualism—place an emphasis on the communitarian and cooperative aspects of anarchist theory; while also opposing authoritarian forms of communitarianism associated with groupthink and collective conformity, instead favouring a reconciliation between individuality and sociality
- considered an umbrella term which includes (but is not limited to) the post-capitalist economic models of anarchist communism, collectivist anarchism, and (sometimes) mutualism; as well as the trade union strategy of anarcho-syndicalism, the social struggle strategies of platformism and specifism, and the environmental philosophy of social ecology
- "social anarchism" is often used interchangeably with libertarian socialism, left-libertarianism, or left anarchism. It emerged in the late 19th century as a distinction from individualist anarchism
- More recent developments within social anarchism are the post-capitalist economic models of inclusive democracy, and participatory economics, both of which could be regarded as updated forms of the collectivist anarchism of Mikhail Bakunin, as well as the environmental philosophy of social ecology, and its associated politics of Post-Scarcity Anarchism and Communalism
- tactical unity, theoretical unity, collective responsibility, federalism
** conservatism
*** conservatism
from http://www.kirkcenter.org/index.php/detail/ten-conservative-principles/:
- "enduring moral order" - That order is made for man, and man is made for it: human nature is a constant, and moral truths are permanent. Meaning... there is a way things are supposed to be?
- adheres tocustom, convention, and continuity
- importance of "prescription" - things established by immemorial usage. Conservatives argue that we are unlikely, we moderns, to make any brave new discoveries in morals or politics or taste. In politics we do well to abide by precedent and precept and even prejudice, for the great mysterious incorporation of the human race has acquired a prescriptive wisdom far greater than any man’s petty private rationality.
- importance of "prudence" - Any public measure ought to be judged by its probable long-run consequences, not merely by temporary advantage or popularity. Liberals and radicals, the conservative says, are imprudent: for they dash at their objectives without giving much heed to the risk of new abuses worse than the evils they hope to sweep away.
- importance of "variety" - They feel affection for the proliferating intricacy of long-established social institutions and modes of life, as distinguished from the narrowing uniformity and deadening egalitarianism of radical systems. For the preservation of a healthy diversity in any civilization, there must survive orders and classes, differences in material condition, and many sorts of inequality. The only true forms of equality are equality at the Last Judgment and equality before a just court of law; all other attempts at levelling must lead, at best, to social stagnation. Society requires honest and able leadership; and if natural and institutional differences are destroyed, presently some tyrant or host of squalid oligarchs will create new forms of inequality.
- importance of "imperfectability" - Human nature suffers irremediably from certain grave faults, the conservatives know. Man being imperfect, no perfect social order ever can be created. (Humans are imperfect and not perfectible).
- "freedom and property are closely linked"
- voluntary community over "involuntary collectivism" - something about prefering decisions to be made locally... not sure what it has to do with collectivism
- "prudent restraints on power and human passions"
- "permancene and change must be recognized and reconciled in a vigorous society"
from wikipedia:
- promotes retaining traditional social institutions in the context of culture and civilization
- seek to preserve institutions like the Church, monarchy and the social hierarchy as they are, emphasizing stability and continuity, while the more extreme elements called reactionaries oppose Modernism and seek a return to "the way things were"
- There is no single set of policies that are universally regarded as conservative, because the meaning of conservatism depends on what is considered traditional in a given place and time. Thus conservatives from different parts of the world—each upholding their respective traditions—may disagree on a wide range of issues.
- political theorists such as Corey Robin define conservatism primarily in terms of a general defense of social and economic inequality. From this perspective conservatism is less an attempt to uphold traditional institutions and more "a meditation on—and theoretical rendition of—the felt experience of having power, seeing it threatened, and trying to win it back."
- Both conservative and liberal parties tend to favor private ownership of property, in opposition to communist, socialist and green parties, which favor communal ownership or laws requiring social responsibility on the part of property owners. Where conservatives and liberals differ is primarily on social issues. Conservatives tend to reject behavior that does not conform to some social norm. Modern conservative parties often define themselves by their opposition to liberal or labor parties. The United States usage of the term conservative is unique to that country
*** american conservatism
- broad system of political beliefs in the United States that is characterized by respect for American traditions, support for Judeo-Christian values, economic liberalism, anti-communism, advocacy of American exceptionalism, and a defense of Western culture from perceived threats posed by "creeping socialism", moral relativism, multiculturalism, and liberal internationalism
-  Liberty is a core value, with a particular emphasis on strengthening the free market, limiting the size and scope of government, and opposition to high taxes and government or labor union encroachment on the entrepreneur
- consider individual liberty, within the bounds of conformity to American values, as the fundamental trait of democracy, which contrasts with modern American liberals, who generally place a greater value on equality and social justice
*** liberal conservatism
- a political ideology combining conservative policies with liberal stances, especially on economic and social issues, or a brand of political conservatism strongly influenced by liberalism. It is a political position which incorporates support for civil liberties and capitalism, along with some social-conservative positions
- usually contrasts with aristocratic conservatism, which rejects the principle of equality as something in discordance with human nature, and emphasizes instead the idea of natural inequality
- often referred to the combination of economic liberalism, which champions laissez-faire markets, with the classical conservatism concern for established tradition, respect for authority and religious values. It contrasted itself with classical liberalism, which supported freedom for the individual in both the economic and social spheres
- Over time, the general conservative ideology in many countries adopted economic liberal arguments, and the term liberal conservatism was replaced with conservatism. This is also the case in countries where liberal economic ideas have been the tradition, such as the United States, and are thus considered conservative.
- liberal conservative tradition in the United States combines the economic individualism of the classical liberals with a Burkean form of conservatism 
- A secondary meaning for the term liberal conservatism that has developed in Europe is a combination of more modern conservative (less traditionalist) views with those of social liberalism. This has developed as an opposition to the more collectivist views of socialism. Often this involves stressing what are now conservative views of free-market economics and belief in individual responsibility, with social liberal views on defence of civil rights, environmentalism and support for a limited welfare state.
- As conservatives in democratic countries have embraced typical liberal institutions such as the rule of law, private property, the market economy, and constitutional representative government, the liberal element of liberal conservatism became consensual among conservatives
- In some countries (e.g. the United Kingdom and the United States) the term "liberal conservatism" came to be understood simply as "conservatism" in popular culture, prompting some conservatives who embraced more strongly classical liberal values to call themselves "libertarians".
- the liberal-conservative tradition in the United States often combines the economic individualism of classical liberals with a Burkean form of conservatism that emphasizes the natural inequalities between men, the irrationality of human behavior as the basis for the human drive for order and stability, and the rejection of natural rights as the basis for government. However, from a different perspective, American conservatism, a "hybrid of conservatism and classical liberalism", has exalted three tenets of Burkean conservatism, namely the diffidence toward the power of the state, the preference of liberty over equality and patriotism, while rejecting the three remaining tenets, namely loyalty to traditional institutions and hierarchies, scepticism regarding progress and elitism. Consequently, in the United States the term "liberal conservatism" is not used and American modern liberalism happens to be quite different from the European brand. The opposite is true in Latin America, where economically liberal conservatism is often labelled under the rubric of neoliberalism both in popular culture and academic discourse.
- European liberal conservatives, in their embracement of liberal and free-market principles, are clearly distinguishable from those conservatives who have embraced national-conservative views, more socially conservative stances and/or outright populism, let alone a right-wing populist posture
- Compared to traditional centre-right politics, such as those proposed by Christian democrats, liberal conservatism is less traditionalist and more right-libertarian economically, favouring low taxes and minimal state intervention in the economy
- This position is also associated with support for moderate forms of social safety net and environmentalism
*** conservative liberalism
- a variant of liberalism that combines liberal values and policies with conservative stances, or, more simply, the right wing of the liberal movement
- a more positive and less radical variant of classical liberalism.
- Conservative liberal parties tend to combine market liberal policies with more traditional stances on social and ethical issues.
- Instead of following progressive liberalism, conservative liberals draw upon pre-modern sources, such as classical philosophy (with its ideas of virtue, the common good, and natural rights), Christianity (with its ideas of natural law, the social nature of man, and original sin), and ancient institutions (such as common law, corporate bodies, and social hierarchies). This gives their liberalism a conservative foundation.
*** libertarian conservatism
- describes certain political ideologies within the United States and Canada which combine libertarian economic issues with aspects of conservatism. Its four main branches are Constitutionalism, paleolibertarianism, small government conservatism and Christian libertarianism. They generally differ from paleoconservatives, in that they are in favor of more personal and economic freedom.
- sometimes called right-libertarianism
- combines right-libertarian politics and conservative values
- In contrast to paleoconservatives, libertarian conservatives support strict laissez-faire policies such as free trade, opposition to any national bank and opposition to business regulations. They are vehemently opposed to environmental regulations, corporate welfare, subsidies, and other areas of economic intervention
- Libertarian conservatives' first value is negative liberty to achieve socially and culturally conservative ends. They reject liberal social engineering.
- combine the advocacy of economic principles, such as fiscal discipline, respect for contracts, defense of private property and free markets and the classical conservative stress on self-help and freedom of choice under a laissez-faire and economically liberal capitalist society with social tenets such as the importance of religion, and the value of traditional morality through a framework of limited, constitutional, representative government
- continued libertarian opposition to "all forms of government intervention – economic, cultural, social, international" but also upholding cultural conservatism in social thought and behavior. They opposed a licentious libertarianism which advocated "freedom from bourgeois morality, and social authority."
*** fiscal conservatism
- Fiscal conservatism is the economic philosophy of prudence in government spending and debt... government does not have the right to run up large debts and then throw the burden on the taxpayer
- a political-economic philosophy regarding fiscal policy and fiscal responsibility advocating low taxes, reduced government spending and minimal government debt
- Free trade, deregulation of the economy, lower taxes, and privatization are defining qualities of fiscal conservatism
- Fiscal conservatism follows the same philosophical outlook of classical liberalism and economic liberalism regarding fiscal matters
- Fiscal conservatives advocate the avoidance of deficit spending, the reduction of overall government spending and national debt, and ensuring balanced budgets. In other words, fiscal conservatives are against the government expanding beyond its means through debt.
- Most conservatives, especially in the United States, believe that government action should focus on moral and social questions and oppose government action to help the poor, to regulate the economy, or to protect the environment. They believe that government programs that seek to provide services and opportunities for the poor actually encourage dependence and reduce self-reliance. They oppose affirmative action. They oppose a progressive income tax.
- Many conservatives, especially in the United States, believe that the government should not play a major role in regulating business and managing the economy. They typically oppose efforts to charge high tax rates and to redistribute income to assist the poor. Such efforts, they argue, do not properly reward people who have earned their money through hard work
- (make sure to also include assumptions here - that wealth is a direct result of hard work, etc.)
*** national conservatism
- a political term used primarily in Europe to describe a variant of conservatism which concentrates more on national interests than standard conservatism as well as upholding cultural and ethnic identity, while not being outspokenly nationalist or supporting a far-right approach
- heavily oriented towards the traditional family and social stability as well as in favour of limiting immigration. As such, national conservatives can be distinguished from economic conservatives, for whom free market economic policies, deregulation and fiscal conservatism are the main priorities.
- concentrates more on national interests and upholding cultural and ethnic identity than most other conservatives
- are "socially traditional" and support the traditional family and social stability
- Many national conservatives are thus social conservatives, as well as in favour of limiting immigration and enacting law-and-order policies
- National conservative parties in different countries do not necessarily share a common position on economic policy: their views may range from support of a planned economy to a centrist mixed economy to a laissez-faire approach.[1] In the first, more common, case, national conservatives can be distinguished from fiscal conservatives,[6] for whom free market economic policies, deregulation and tight spending are the main priorities
*** traditionalist conservatism / toryism
- set of principles based on concern for established tradition, respect for authority, and religious values
- political philosophy emphasizing the need for the principles of natural law and transcendent moral order, tradition, hierarchy and organic unity, agrarianism, classicism and high culture, and the intersecting spheres of loyalty
- Some traditionalists have embraced the labels "reactionary" and "counterrevolutionary", defying the stigma that has attached to these terms since the Enlightenment.
- Having a hierarchical view of society, many traditionalist conservatives, including a few Americans, defend the monarchical political structure as the most natural and beneficial social arrangement.
(From toryism)
- supported a hierarchical society with a monarch who ruled by divine right
- opposed the idea that sovereignty derived from the people, and rejected the authority of parliament and freedom of religion
- evolved in the early 19th century - Conservatism no longer was the philosophical defense of the landed aristocracy but had been refreshed into redefining its commitment to the ideals of order, both secular and religious, expanding imperialism, strengthened monarchy, and a more generous vision of the welfare state as opposed to the punitive vision of the Whigs and Liberals
- Belief in natural law and transcendent moral order lay the foundation for traditionalist conservative thought. Reason and Divine Revelation inform natural law and the universal truths of faith. It is through these universal truths of faith that man orders himself and the world around him. Mankind organized society on the basis of these universal truths of faith. The traditionalist holds axiomatic the belief that religion precedes civilization
- believe that tradition and custom guide man and his worldview. Each generation inherits the experience and culture of its ancestors and through convention and precedence man is able to pass it down to his descendants
- believe that human society is essentially hierarchical (i.e., it always involves various interdependent inequalities, degrees, and classes and that political structures that recognize this fact prove the most just, thriving, and generally beneficial). Hierarchy allows for the preservation of the whole community simultaneously, instead of protecting one part at the expense of the others
- While most traditionalist conservatives are cosmopolitan[citation needed] and many live in urban centers, the countryside and the values of rural life are prized highly (sometimes even being romanticized, as in pastoral poetry). The principles of agrarianism (i.e., preserving the small family farm, open land, the conservation of natural resource, and stewardship of the land) are central to a traditionalist's understanding of rural life
- defend classical Western civilization, and value an education informed by the texts of the Hebraic, Greek, Roman, and Medieval eras. Similarly, traditionalists are classicists who revere high culture in all of its manifestations (e.g., literature, music, architecture, art, theater)
- Unlike nationalists, who esteem the role of the State or nation over the local or regional community, traditionalists hold up patriotism as a key principle. Traditionalist conservatives think that loyalty to a locality or region is more central than any commitment to a larger political entity. Traditionalists also welcome the value of subsidiarity and the intimacy of one's community, preferring the Civil Society of Burke's "little platoons" over the expanded State. Nationalism, alternately, leads to jingoism and views the state as abstract from the local community and family structure rather than as an outgrowth of these local realities
*** red tory
- adherent of a centre-right or progressive-conservative political philosophy derived from the Tory tradition in Canada and the United Kingdom
- tends to favour liberal social policies, while maintaining a degree of fiscal conservatism and a respect of social and political order
- Canadian conservatism has been derived from the Tory tradition, with a distinctive concern for a balance between individual rights and collectivism, as mediated through a traditional pre-industrial standard of morality – which has never been as evident in American conservatism
- derives largely from a classical conservative tradition that maintained that the unequal division of wealth and political privilege among social classes can be justified if members of the privileged class practiced noblesse oblige and contributed to the common good.
- supported traditional institutions such as religion and the monarchy, and maintenance of the social order
- In distinction to the American experience where class divisions were seen as undemocratic (although still existing), Canadian Tories adopted a more paternalistic view of government. Monarchy, public order and good government – understood as dedication to the common good – preceded, moderated and balanced an unequivocal belief in individual rights and liberty
- The explicit notion of a "Red" Toryism was developed by Gad Horowitz in the 1960s, who argued that there was a significant Tory ideology in Canada. This vision contrasted Canada with the United States, which was seen as lacking this collectivist tradition because it was expunged from the American political culture after the American Revolution and the exodus of the United Empire Loyalists. 
- The term Red Tory is often used today in the media not to refer to those in the tradition of George Grant, Dalton Camp or Robert Stanfield, but simply to moderates in the conservative movement, particularly those who reject or do not sufficiently embrace social conservatism.
*** small c conservative
*** cultural conservatism
- support the preservation of the heritage of one nation, or of a shared culture that is not defined by national boundaries.
- Other variants of cultural conservatism are concerned with culture attached to a given language
- hold fast to traditional ways of thinking even in the face of monumental change. They believe strongly in traditional values and traditional politics, and often have an urgent sense of nationalism.
- distinct from social conservatism, although there are some overlaps. Social conservatives believe that the government has a role in encouraging or enforcing what they consider traditional values or behaviors. A social conservative wants to preserve traditional morality and social mores, often through civil law or regulation. Social change is generally regarded as suspect
*** social conservatism
- group of political ideologies centred on preserving traditional beliefs, attitudes and philosophy. The aims of social conservatism vary from organisation to organisation, and from country to country. Thus, there are really no policies or positions that could be considered universal among social conservatives.
- may believe that the government has a role in encouraging or enforcing traditional values or behaviours
- wants to preserve traditional morality and social mores, often by opposing what they consider radical policies or social engineering. 
- Social change is generally regarded as suspect
- A second meaning of the term social conservatism developed in the Nordic countries and continental Europe. There it refers to liberal conservatives supporting modern European welfare states.
- Social conservatives (in the first meaning of the word) in many countries generally favour the pro-life position in the abortion controversy and oppose human embryonic stem cell research (particularly if publicly funded); oppose both eugenics and human enhancement (transhumanism) while supporting bioconservatism; support a traditional definition of marriage as being one man and one woman; view the nuclear family model as society's foundational unit; oppose expansion of civil marriage and child adoption rights to couples in same-sex relationships; promote public morality and traditional family values; oppose atheism, especially militant atheism, secularism and the separation of church and state; support the prohibition of drugs, prostitution, and euthanasia; and support the censorship of pornography and what they consider to be obscenity or indecency. Most conservatives in the US support the death penalty.
list of specific parties: https://en.wikipedia.org/wiki/Social_conservatism
*** religions conservatism
- seek to apply the teachings of particular religions to politics, sometimes by merely proclaiming the value of those teachings, at other times by having those teachings influence laws
- typically oppose abortion, homosexual behavior, drug use, and sexual activity outside of marriage
*** progressive conservatism
- incorporates progressive policies alongside conservative policies
- stresses the importance of a social safety net to deal with poverty, support of limited redistribution of wealth along with government regulation to regulate markets in the interests of both consumers and producers
- basically center-right
*** authoritarian conservatism
- refers to autocratic regimes that center their ideology around conservative nationalism rather than ethnic nationalism, though certain racial components such as antisemitism may exist
- show strong devotion towards religion, tradition, and culture, while also expressing fervent nationalism akin to other far-right nationalist movements
- Authoritarian conservative movements were prominent in the same era as fascism, with which it sometimes clashed. Although both ideologies shared core values such as nationalism and had common enemies such as communism and materialism, there was nonetheless a contrast between the traditionalist nature of authoritarian conservatism and the revolutionary, palingenetic, and populist nature of fascism; thus, it was common for authoritarian conservative regimes to suppress rising fascist and National Socialist movements. The hostility between the two ideologies is highlighted by the struggle for power for the National Socialists in Austria, which was marked by the assassination of Dollfuss.
*** regional variants
Interesting to split these out into different things and tag them with the specific movement they're from
https://en.wikipedia.org/wiki/Conservatism#Historic_conservatism_in_different_countries
https://en.wikipedia.org/wiki/Conservatism#Modern_conservatism_in_different_countries
https://en.wikipedia.org/wiki/Conservatism#Characteristics_of_conservatism_in_France.2C_Italy.2C_Russia.2C_Poland.2C_UK.2C_US_and_Israel
https://en.wikipedia.org/wiki/List_of_political_ideologies#Regional_variants
*** reactionary
- a person who holds political views that favor a return to the status quo ante, the previous political state of society, which they believe possessed characteristics (discipline, respect for authority, etc.) that are negatively absent from the contemporary status quo of a society. As an adjective, the word reactionary describes points of view and policies meant to restore the status quo ante
- Political reactionaries are at the right-wing of a political spectrum; yet, reactionary ideologies can be radical, in the sense of political extremism, in service to re-establishing the status quo ante
*** neoreactionary
- objectives included opposition to any form of egalitarianism as well as "a return to traditional gender roles, monarchism, and typically a more libertarian-oriented economic system"
*** paleoconservatism
- stressing tradition, limited government and civil society, along with religious, regional, national and Western identity.
- paleoconservatives press for restrictions on immigration, a rollback of multicultural programmes, the decentralization of the federal policy, the restoration of controls upon free trade, a greater emphasis upon economic nationalism and isolationism in the conduct of American foreign policy, and a generally revanchist outlook upon a social order in need of recovering old lines of distinction and in particular the assignment of roles in accordance with traditional categories of gender, ethnicity, and race
- claim to represent a more historic, authentic conservative tradition than that found in neoconservatism.
- Just as paleoconservatives' non-interventionism stems from their skepticism as to what extent—if at all—European culture can be transplanted or forced upon non-Western cultures, paleoconservatives' opposition to immigration is rooted in their skepticism of the ability of non-Western peoples to adopt European culture. As a result, paleocons are most distinctive in their emphatic opposition to open immigration by non-Europeans, and their general disapproval of U.S. intervention overseas. Sam Francis wrote:
We believe that the United States derives from and is an integral part of European civilization and the European people and that the American people and government should remain European in their composition and character. We therefore oppose the massive immigration of non-European and non-Western peoples into the United States that threatens to transform our nation into a non-European majority in our lifetime. We believe that illegal immigration must be stopped, if necessary by military force and placing troops on our national borders; that illegal aliens must be returned to their own countries; and that legal immigration must be severely restricted or halted through appropriate changes in our laws and policies.
- They are also strongly critical of neoconservatives and their sympathizers in print media, talk radio and cable TV news. Paleocons often say they are not conservatives in the sense that they necessarily wish to preserve existing institutions or seek merely to slow the growth of modern big-government conservatism. They do not wish to be closely identified with the U.S. Republican Party. Rather, they seek the renewal of "small 'r'" republican society in the context of the Western heritage, customs and civilization. Joseph Scotchie wrote:
Republics mind their own business. Their governments have very limited powers, and their people are too busy practicing self-government to worry about problems in other countries. Empires not only bully smaller, defenseless nations, they also can't leave their own, hapless subjects alone.... Empires and small government aren't compatible, either.
- paleocons see neoconservatives as empire-builders and themselves as defenders of the republic
- On some issues, many paleocons are hard to distinguish from others on the conservative spectrum. For example, they tend to oppose abortion on demand and gay marriage, while supporting capital punishment, handgun ownership and an original intent reading of the U.S. Constitution. On the other hand, paleocons are often more sympathetic to environmental protection, animal welfare, and anti-consumerism than others on the US Right
- Paleoconservatives argue that since human nature is limited and finite, any attempt to create a man-made utopia is headed for disaster and potential carnage. Instead, they lean toward tradition, family, customs, religious institutions and classical learning to provide wisdom and guidance
- Among the most dangerous of our theoretical illusions are the political fantasies that can be summed up in words like democracy; equality, and natural rights; the principle of one man, one vote and the American tradition of self-government. No one who lives in the world with his eyes open can actually believe in any of this.
- Many paleocons also say that Westerners have lost touch with their classical and European heritage, to the point that they are in danger of losing their civilization. Robert S. Griffin notes that paleocons fear the United States becoming a "secularized, homogenized, de-Europeanized, pacified, deluded, manipulated, lowest-common-denominator-leveled, popular-culture-dopified country"
- Anti-Federalism is another key aspect of paleoconservatism, which adherents see as an antitype to the managerial state. The paleocon flavor urges honoring the principle of subsidiarity, that is, decentralized government, local rule, private property and minimal bureaucracy.
- anti-individualism? a recognition that man is a social and political animal who cannot be treated as an "individual" without doing damage to human nature. In this sense libertarian theory is as wrong and as potentially harmful as communism. The commonwealth is therefore a natural and necessary expression of human nature that provides for the fulfillment of human needs
- The family is the natural and fundamental social unit, inscribed in our nature as human beings, rooted in marriage, rooted in the commitment to bring new life into the world, and rooted in a deep respect for both ancestors and posterity, where family is "a man and a woman living in a socially sanctioned bond called marriage for the purposes of propagating and rearing children, sharing intimacy and resources, and conserving lineage, property, and tradition."
- heterosexual marriage is hard-coded into human nature
- question the validity of gender feminism in similar ways, some questioning feminism in both its radical and moderate forms. They say that the push for total gender equality dehumanizes both men and women, damaging the nuclear family and sacralizing abortion.
- men and women "are different in reproductive, economic, and social functions", even though they share political and property rights.
- "the laws and decrees enacted by human government are mutable and sometimes tyrannical", yet "the laws of human nature, worked tight within the spirals of the genetic code, are unchanging and just."
*** neoconservatism
- political movement born in the United States during the 1960s among conservative-leaning Democrats who became disenchanted with the party's foreign policy
- The term "neoconservative" refers to those who made the ideological journey from the anti-Stalinist Left to the camp of American conservatism
- Neoconservatives typically advocate the promotion of democracy and American national interest in international affairs, including by means of military force and are known for espousing disdain for communism and for political radicalism
- In foreign policy, the neoconservatives' main concern is to prevent the development of a new rival
- communism was a monstrous evil and a potent danger
- first developed during the late 1960s as an effort to oppose the radical cultural changes occurring within the United States. Irving Kristol wrote: "If there is any one thing that neoconservatives are unanimous about, it is their dislike of the counterculture."
- stress on foreign affairs "emerged after the New Left and the counterculture had dissolved as convincing foils for neoconservatism .... The essential source of their anxiety is not military or geopolitical or to be found overseas at all; it is domestic and cultural and ideological."
- Neoconservative foreign policy is a descendant of so-called Wilsonian idealism. Neoconservatives endorse democracy promotion by the U.S. and other democracies, based on the claim that they think that human rights belong to everyone. They criticized the United Nations and detente with the USSR. On domestic policy, they endorse a welfare state, like European and Canadian conservatives and unlike American conservatives.
- While neoconservatism is concerned primarily with foreign policy, there is also some discussion of internal economic policies. Neoconservatism generally endorses free markets and capitalism, favoring supply-side economics, but it has several disagreements with classical liberalism and fiscal conservatism: Irving Kristol states that neocons are more relaxed about budget deficits and tend to reject the Hayekian notion that the growth of government influence on society and public welfare is "the road to serfdom." Indeed, to safeguard democracy, government intervention and budget deficits may sometimes be necessary, Kristol argues
- Further, neoconservative ideology stresses that while free markets do provide material goods in an efficient way, they lack the moral guidance human beings need to fulfill their needs. Morality can be found only in tradition, they say and, contrary to libertarianism, markets do pose questions that cannot be solved solely by economics. "So, as the economy only makes up part of our lives, it must not be allowed to take over and entirely dictate to our society."
*** theoconservatism
- political labels referring to members of the Christian right, particularly those whose ideology represents a synthesis of elements of American conservatism, conservative Christianity, and social conservatism, expressed through political means
- [T]he neoconservatives believe that America is special because it was founded on an idea—a commitment to the rights of man embodied in the Declaration of Independence—not in ethnic or religious affiliations. The theocons, too, argue that America is rooted in an idea, but they believe that idea is Christianity.
*** right-wing populism
- a political ideology that rejects the current political consensus and often combines laissez-faire, ethnocentrism and anti-elitism.
- It is considered populism because of its appeal to the "common man" as opposed to the elites
- In Europe, right-wing populism is also an expression used to describe groups and political parties generally known for their opposition to immigration, mostly from the Islamic world and, in some cases, from (other members of) the European Union. 
- Traditional right-wing views such as opposition to an increasing support for the welfare state and a "more lavish, but also more restrictive, domestic social spending" scheme is also described under right-wing populism and is sometimes called "welfare chauvinism"
- Right-wing populism is distinct from conservativism but several right-wing populist parties have their roots in conservative political parties. Still others have links to fascist movements founded during the interwar period when Italian, German, Hungarian, Spanish and Japanese fascism rose to power.
- Classification of right-wing populism into a single political family has proved difficult, and it is not certain whether a meaningful category exists, or merely a cluster of categories, since the parties differ in ideology, organization, and leadership rhetoric. Also, unlike traditional parties, they do not belong to international organizations of like-minded parties, and they do not use similar terms to describe themselves. One commonality though is that they are more right-wing than other political parties on the left–right axis.
- specific examples: https://en.wikipedia.org/wiki/Right-wing_populism#By_country
*** radical right
*** right-libertarianism
- refers to libertarian political philosophies that advocate negative rights, and a radical reversal of the modern welfare state
- strongly support private property rights, and defend unequal "distribution" of natural resources and private property. This position is contrasted with that of some versions of left-libertarianism, which maintain that natural resources belong to everyone in some egalitarian manner, either unowned or owned collectively.
- Right-libertarianism includes anarcho-capitalism and laissez-faire, minarchist liberalism.
- non-aggression principle
- There is a debate amongst right-libertarians as to whether or not the state is legitimate: while anarcho-capitalists advocate its abolition, minarchists support minimal states, often referred to as night-watchman states.
- minarchist right-libertarians justify the state on the grounds that it is the logical consequence of adhering to the non-aggression principle and argue that anarchism is immoral because it implies that the non-aggression principle is optional, that the enforcement of laws under anarchism is open to competition. Another common justification is that private defense agencies and court firms would tend to represent the interests of those who pay them enough
- Anarcho-capitalists argue that the state violates the non-aggression principle by its nature because governments use force against those who have not stolen or vandalized private property, assaulted anyone, or committed fraud. Many also argue that monopolies tend to be corrupt and inefficient, that private defense and court agencies would have to have a good reputation in order to stay in business.
- anarcho-capitalists argue that no coercive monopoly of force can arise on a truly free market and that a government's citizenry can't desert them in favor of a competent protection and defense agency
- Libertarian philosopher Moshe Kroy argues that the disagreement between anarcho-capitalists who adhere to Murray Rothbard's view of human consciousness and the nature of values and minarchists who adhere to Ayn Rand's view of human consciousness and the nature of values over whether or not the state is moral is not due to a disagreement over the correct interpretation of a mutually held ethical stance. He argues that the disagreement between these two groups is instead the result of their disagreement over the nature of human consciousness and that each group is making the correct interpretation of their differing premises. These two groups are therefore not making any errors with respect to deducing the correct interpretation of any ethical stance because they do not hold the same ethical stance
- there is debate on whether left, right, and socialist libertarianism "represent distinct ideologies as opposed to variations on a theme," right-libertarianism is most in favor of private property
- Right-libertarians maintain that unowned natural resources "may be appropriated by the first person who discovers them, mixes his labor with them, or merely claims them—without the consent of others, and with little or no payment to them. This contrasts with left-libertarianism in which "unappropriated natural resources belong to everyone in some egalitarian manner. Right-libertarians believe that natural resources are originally unowned, and therefore, private parties may appropriate them at will without the consent of, or owing to, others (e.g. a land value tax).
- Right-libertarians (also referred to as propertarians) hold that societies in which private property rights are enforced are the only ones that are both ethical and lead to the best possible outcomes. They generally support the free market, and are not opposed to any concentrations of economic power, provided it occurs through non-coercive means.
*** monarchism
- advocacy of a monarch or monarchical rule
- A monarchist is an individual who supports this form of government, independent of any specific monarch; one who espouses a particular monarch is a royalist. Conversely, the opposition to monarchical rule is sometimes referred to as republicanism
*** green conservatism
- a subset of conservatives who have incorporated green concerns into their ideology
*** compassionate conservatism
- political philosophy that stresses using traditionally conservative techniques and concepts in order to improve the general welfare of society
- Wead contended that the policies of Republican conservatives should be motivated by compassion, not protecting the status quo. And Wead declared himself to be "a bleeding heart conservative," meaning that he cared for people and sincerely believed that a free marketplace was better for the poor
- Compassionate conservatism has been defined as the belief that conservatism and compassion complement each other. A compassionate conservative might see the social problems of the United States, such as health care or immigration, as issues that are better solved through cooperation with private companies, charities and religious institutions rather than directly through government departments
- Compassionate conservatives [...] offer a new way of thinking about the poor. They know that telling the poor that they are mere passive victims, whether of racism or of vast economic forces, is not only false but also destructive, paralyzing the poor with thoughts of their own helplessness and inadequacy. The poor need the larger society's moral support; they need to hear the message of personal responsibility and self-reliance, the optimistic assurance that if they try – as they must – they will make it. They need to know, too, that they can't blame "the system" for their own wrongdoing. - Myron Magnet
- Compassionate conservative philosophy argues for policies in support of traditional families, welfare reform to promote individual responsibility (cf. workfare), active policing, standards-based schools (cf. No Child Left Behind Act), and assistance (economic or otherwise) to poor countries around the world
*** civic conservatism
- the idea of focussing on the institutions between the state and individuals as a policy concern (rather than merely thinking of individuals and the state as the only agencies). The pamphlet wished to "place the free market in the context of institutions and values which make up civil society". The examples of these institutions were the "network of voluntary organisations", from hospitals to guilds, which had been "weakened if not destroyed by the advance of the State"
- Civic conservatism, like free market economics, proceeds from deep-seated individual self-interest towards a stable cooperation. It sets the Tories the task not of changing humanity but of designing institutions and arrangements that encourage our natural reciprocal altruism
*** bioconservatism
- a stance of hesitancy about technological development especially if it is perceived to threaten a given social order
- conrasting stance to techno-progressivism
- Strong bioconservative positions include opposition to genetic modification of food crops, the cloning and genetic engineering of livestock and pets, and, most prominently, rejection of the genetic, prosthetic, and cognitive modification of human beings to overcome what are broadly perceived as current human biological and cultural limitations
- What unifies bioconservatives is skepticism about medical and other biotechnological transformations of the living world.
- Typically less sweeping as a critique of technological society than bioluddism, the bioconservative perspective is characterized by its defense of the natural, deployed as a moral category
*** anti-communism
- opposition to communism
- Conservative and classical liberal anti-communists argue that centrally planned economies have under-performed free market economies in economic growth and say that communism results in lower liberty. 
- Some anti-communists refer to both communism and fascism as totalitarianism, seeing similarity between the actions of communist and fascist governments
*** agrarianism
- is a social philosophy or political philosophy which values rural society as superior to urban society, the independent farmer as superior to the paid worker, and sees farming as a way of life that can shape the ideal social values. It stresses the superiority of a simpler rural life as opposed to the complexity of city life.
- Farming is the sole occupation that offers total independence and self-sufficiency.
- Urban life, capitalism, and technology destroy independence and dignity and foster vice and weakness.
- The agricultural community, with its fellowship of labor and co-operation, is the model society.
- The farmer has a solid, stable position in the world order. He "has a sense of identity, a sense of historical and religious tradition, a feeling of belonging to a concrete family, place, and region, which are psychologically and culturally beneficial." The harmony of his life checks the encroachments of a fragmented, alienated modern society.
- Cultivation of the soil "has within it a positive spiritual good" and from it the cultivator acquires the virtues of "honor, manliness, self-reliance, courage, moral integrity, and hospitality." They result from a direct contact with nature and, through nature, a closer relationship to God. The agrarian is blessed in that he follows the example of God in creating order out of chaos.
** right-wing politics
** left-wing politics
** liberalism
*** libertarianism
**** geolibertarianism
**** objectivism
** communism
*** communist egoism
- The perspective of communist egoism is the perspective of that selfishness which desires nothing so much as other selves, of that egoism which wants nothing so much as other egos; of that greed which is greedy to love—love being the 'total appropriation' of man by man
** socialism
*** libertarian socialism
- 
*** participatory economics
** various "techno-" and "transhuman" things
where to find a list / enumeration of these things?
https://en.wikipedia.org/wiki/Transhumanism ?
http://ieet.org/index.php/IEET/biopolitics !!
*** technoprogressivism
- social wage, universal healthcare, basic income, ...
*** singularitarianism
*** bioconservativism
*** collaborative e-democracy
** political obligation
http://www.iep.utm.edu/poli-obl/#H8
- there IS a moral obligation to do what the law requires just because the law requires it ("political obligation")
- there IS NOT a moral obligation to do what the law requires just because the law requires it
** nationalism
*** alt-right / neoreactionary / gamergate / etc.
http://www.breitbart.com/tech/2016/03/29/an-establishment-conservatives-guide-to-the-alt-right/
https://pbs.twimg.com/media/CzH1TR2WgAAhnW_.jpg
https://en.wikipedia.org/wiki/Talk:Alt-right
- not sure they have any new ideas
- call them what they are - white nationalists, male chauvinists
- probably some connection to nietzsche / "great men"
** feminism
*** gender feminism
*** equity feminism
** relevant ideas
whatever other things you come across
might make sense to express other ideologies as collections of these
*** pro-globalization / free trade
*** social justice
*** anti-globalization
*** pro-capitalism
*** anti-capitalism
*** anti-socialism
*** postcapitalism
*** pro-slavery
*** anti-slavery
*** nihilism
*** existentialism
*** structuralism
*** post-structuralism
- 
*** post-modernism
*** anti-individualism
- what seems to be internal to the individual is to some degree dependent on the social environment. Thus, self-knowledge, intentions, reasoning and moral value may variously be seen as being determined by factors outside the person
- argue for a limited agreement with the Cartesian model of self-cognition as being Authoritative, but also pointed out that knowledge of self-cognition was not always absolute, allowing for the individuation of thought to originate from both the external content of our environment, as well as from the internal landscape of our self-knowledge as it is still being discovered: "One can know what one's mental events are and yet not know relevant general facts about the conditions for individuating those events. It is simply not true that the cogito gives us knowledge of the individuation conditions of our thoughts which enables us to "shut off" their individuation conditions from the physical environment"
*** collectivism + critiques
*** individualism + critiques
*** ethical egoism
*** Anarchism and Friedrich Nietzsche
https://en.wikipedia.org/wiki/Anarchism_and_Friedrich_Nietzsche
- Nietzsche's Übermensch was representative of the freedom for people to define the nature of their own existence, as well as the desire for a new human who was to be neither master nor slave.
- Nietzsche's idealized individual invents his or her own values and creates the very terms under which they excel, taking no regard for God, the state, or the social behavior of 'herds'
*** might makes right
*** situationism
- The intellectual foundations of the Situationist International were derived primarily from anti-authoritarian Marxism and the avant-garde art movements of the early 20th century, particularly Dada  and Surrealism
- situationist theory represented an attempt to synthesize this diverse field of theoretical disciplines into a modern and comprehensive critique of mid-20th century advanced capitalism
- recognized that capitalism had changed since Marx's formative writings, but maintained that his analysis of the capitalist mode of production remained fundamentally correct; they rearticulated and expanded upon several classical Marxist concepts, such as his theory of alienation
- In their expanded interpretation of Marxist theory, the situationists asserted that the misery of social alienation and commodity fetishism were no longer limited to the fundamental components of capitalist society, but had now in advanced capitalism spread themselves to every aspect of life and culture
- rejected the idea that advanced capitalism's apparent successes—such as technological advancement, increased income, and increased leisure—could ever outweigh the social dysfunction and degradation of everyday life that it simultaneously inflicted
- Essential to situationist theory was the concept of the spectacle, a unified critique of advanced capitalism of which a primary concern was the progressively increasing tendency towards the expression and mediation of social relations through objects
- The situationists believed that the shift from individual expression through directly lived experiences, or the first-hand fulfillment of authentic desires, to individual expression by proxy through the exchange or consumption of commodities, or passive second-hand alienation, inflicted significant and far-reaching damage to the quality of human life for both individuals and society
- Another important concept of situationist theory was the primary means of counteracting the spectacle; the construction of situations, moments of life deliberately constructed for the purpose of reawakening and pursuing authentic desires, experiencing the feeling of life and adventure, and the liberation of everyday life

*** non-primitivist critiques of civilization
*** master-slave morality
*** transcendentalism
*** post-WWII liberal humanism?
- multiculturalist tolerance and celebration of different identities; solicitude for how your own behavior affects others; concern for the social impact of language, etc. But the history of the term “politically correct” tells a much different story.
*** positive and negative rights
*** moral relativism and anti-relativism
*** cultural relativism?
*** intersectionality
all types of oppression are linked and must be eradicated
*** patriotism
(differences with nationalism)
*** social dominance orientation
https://en.wikipedia.org/wiki/Social_dominance_orientation
"While age- and gender-based hierarchies will tend to exist within all social systems, arbitrary-set systems of social hierarchy will invariably emerge within social systems producing sustainable economic surpluses.
Most forms of group conflict and oppression (e.g., racism, homophobia, ethnocentrisim, sexism, classism, regionalism) can be regarded as different manifestations of the same basic human predisposition to form group-based hierarchies.
Human social systems are subject to the counterbalancing influences of hierarchy-enhancing (HE) forces, producing and maintaining ever higher levels of group-based social inequality, and hierarchy-attenuating (HA) forces, producing greater levels of group-based social equality."

Really good items!
https://en.wikipedia.org/wiki/Social_dominance_orientation#Scale
*** jingoism
*** civil society
*** historicism
*** rule of law
*** private property
*** market economy
*** constitutional representative government
*** welfare chauvinism
*** opposition to immigration
*** non-aggression principle
- often described as the foundation of present-day right-libertarian philosophies
- a moral stance which forbids actions that are inconsistent with capitalist property rights; defines "aggression" and "initiation of force" as violation of these rights
- NAP and property rights are closely linked, since what constitutes aggression depends on what libertarians consider to be one's property
- Because the principle redefines aggression in right-libertarian terms, use of the NAP as a justification for right-libertarianism has been criticized as circular reasoning and as rhetorical obfuscation of the coercive nature of libertarian property law enforcement
- The principle has been used rhetorically to oppose such policies as victimless crime laws, taxation, and military drafts.
*** minarchism
- Minarchists maintain that the state is necessary for the protection of individuals from aggression, theft, breach of contract, and fraud. 
- They believe the only legitimate governmental institutions are the military, police, and courts, though some expand this list to include fire departments, prisons, and the executive and legislative branches
*** protectionism
- the economic policy of restraining trade between states (countries) through methods such as tariffs on imported goods, restrictive quotas, and a variety of other government regulations
- Protectionist policies protect the producers, businesses and workers of the import-competing sector in a country from foreign competitors
- According to proponents, these policies can counteract unfair trade practices, to allow fair competition between imports and goods and services produced domestically
- Protectionists may favor the policy in order to decrease the trade deficit, maintain employment in certain sectors, or favor the growth of certain industries
- specific policies: https://en.wikipedia.org/wiki/Protectionism#Protectionist_policies
*** non-interventionism
- a foreign policy that holds that political rulers should avoid alliances with other nations but still retain diplomacy and avoid all wars unless related to direct self-defense
- non-interventionism is a policy characterized by the absence of "interference by a state or states in the external affairs of another state without its consent, or in its internal affairs with or without its consent
- Non-interventionism is distinct from and often confused with isolationism. Proponents of isolationism differ from proponents of non-interventionism through their advocacy of economic nationalism (called also protectionism) and immigration reduction. Non-interventionism is a policy in government only and thus does not exclude non-governmental intervention by organizations
*** isolationism
- the foreign policy position that a nations' interests are best served by keeping the affairs of other countries at a distance
- A policy or doctrine of trying to isolate one's country from the affairs of other nations by declining to enter into alliances, foreign economic commitments, international agreements, and generally attempting to make one's economy entirely self-reliant; seeking to devote the entire efforts of one's country to its own advancement, both diplomatically and economically, while remaining in a state of peace by avoiding foreign entanglements and responsibilities
- Non-interventionism is distinct from and often confused with isolationism. Proponents of isolationism differ from proponents of non-interventionism through their advocacy of economic nationalism (called also protectionism) and immigration reduction. Non-interventionism is a policy in government only and thus does not exclude non-governmental intervention by organizations
*** federalism
- the mixed or compound mode of government, combining a general government (the central or 'federal' government) with regional governments (provincial, state, cantonal, territorial or other sub-unit governments) in a single political system. Its distinctive feature, exemplified in the founding example of modern federalism of the United States of America under the Constitution of 1787, is a relationship of parity between the two levels of government established. It can thus be defined as a form of government in which there is a division of powers between two levels of government of equal status.
- Federalism is distinguished from confederalism, in which the general level of government is subordinate to the regional level, and from devolution within a unitary state, in which the regional level of government is subordinate to the general level
- Modern federalism is a system based upon democratic rules and institutions in which the power to govern is shared between national and provincial/state governments. The term federalist describes several political beliefs around the world depending on context
*** paternalism
*** communitarianism
- a philosophy that emphasizes the connection between the individual and the community.
- Its overriding philosophy is based upon the belief that a person's social identity and personality are largely molded by community relationships, with a smaller degree of development being placed on individualism
- Although the community might be a family unit, communitarianism usually is understood, in the wider, philosophical sense, as a collection of interactions, among a community of people in a given place (geographical location), or among a community who share an interest or who share a history
- The term is primarily used in two senses: Philosophical communitarianism considers classical liberalism to be ontologically and epistemologically incoherent, and opposes it on those grounds. Unlike classical liberalism, which construes communities as originating from the voluntary acts of pre-community individuals, it emphasizes the role of the community in defining and shaping individuals. Communitarians believe that the value of community is not sufficiently recognized in liberal theories of justice. Ideological communitarianism is characterized as a radical centrist ideology that is sometimes marked by leftism on economic issues and centrism on social issues. This usage was coined recently. When the term is capitalized, it usually refers to the Responsive Communitarian movement of Amitai Etzioni and other philosophers.
- In moral and political philosophy, communitarians are best known for their critiques of John Rawls' political liberalism, detailed at length in his book A Theory of Justice. Communitarians criticize the image Rawls presents of humans as atomistic individuals, and stress that individuals who are well-integrated into communities are better able to reason and act in responsible ways than isolated individuals, but add that if social pressure to conform rises to high levels, it will undermine the individual self
